CREATE TABLE "account_security" (
	"user_id" uuid PRIMARY KEY NOT NULL,
	"failed_login_attempts" integer DEFAULT 0 NOT NULL,
	"last_failed_attempt" timestamp with time zone,
	"locked_until" timestamp with time zone,
	"lockout_reason" varchar(50),
	"max_concurrent_sessions" integer DEFAULT 3 NOT NULL,
	"require_fresh_auth_minutes" integer DEFAULT 5 NOT NULL,
	"password_changed_at" timestamp with time zone,
	"last_password_reset" timestamp with time zone,
	"suspicious_activity_detected" boolean DEFAULT false NOT NULL,
	"mfa_enabled" boolean DEFAULT false NOT NULL,
	"mfa_method" varchar(20),
	"mfa_enforced_at" timestamp with time zone,
	"mfa_skips_remaining" integer DEFAULT 5 NOT NULL,
	"mfa_skip_count" integer DEFAULT 0 NOT NULL,
	"mfa_first_skipped_at" timestamp with time zone,
	"mfa_last_skipped_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "announcement_reads" (
	"announcement_read_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"announcement_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"read_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "uq_announcement_reads" UNIQUE("announcement_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "announcement_recipients" (
	"announcement_recipient_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"announcement_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "uq_announcement_recipients" UNIQUE("announcement_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "announcements" (
	"announcement_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"subject" text NOT NULL,
	"body" text NOT NULL,
	"target_type" text DEFAULT 'all' NOT NULL,
	"publish_at" timestamp with time zone,
	"expires_at" timestamp with time zone,
	"is_active" boolean DEFAULT true NOT NULL,
	"priority" text DEFAULT 'normal' NOT NULL,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "audit_logs" (
	"audit_log_id" varchar(255) PRIMARY KEY NOT NULL,
	"event_type" varchar(50) NOT NULL,
	"action" varchar(100) NOT NULL,
	"user_id" varchar(255),
	"ip_address" varchar(45),
	"user_agent" text,
	"resource_type" varchar(50),
	"resource_id" varchar(255),
	"old_values" text,
	"new_values" text,
	"metadata" text,
	"severity" varchar(20) DEFAULT 'low' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "chart_categories" (
	"chart_category_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chart_categories_chart_category_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"category_name" varchar(100) NOT NULL,
	"category_description" text,
	"parent_category_id" integer,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "chart_data_source_columns" (
	"column_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chart_data_source_columns_column_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"data_source_id" integer NOT NULL,
	"column_name" varchar(100) NOT NULL,
	"display_name" varchar(100) NOT NULL,
	"column_description" text,
	"data_type" varchar(50) NOT NULL,
	"is_filterable" boolean DEFAULT false,
	"is_groupable" boolean DEFAULT false,
	"is_measure" boolean DEFAULT false,
	"is_dimension" boolean DEFAULT false,
	"is_date_field" boolean DEFAULT false,
	"is_measure_type" boolean DEFAULT false,
	"is_time_period" boolean DEFAULT false,
	"is_expansion_dimension" boolean DEFAULT false,
	"expansion_display_name" varchar(100),
	"format_type" varchar(50),
	"sort_order" integer DEFAULT 0,
	"default_aggregation" varchar(20),
	"display_icon" boolean DEFAULT false,
	"icon_type" varchar(20),
	"icon_color_mode" varchar(20) DEFAULT 'auto',
	"icon_color" varchar(50),
	"icon_mapping" jsonb,
	"is_sensitive" boolean DEFAULT false,
	"access_level" varchar(20) DEFAULT 'all',
	"allowed_values" jsonb,
	"validation_rules" jsonb,
	"example_value" text,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "chart_data_sources" (
	"data_source_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chart_data_sources_data_source_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"data_source_name" varchar(100) NOT NULL,
	"data_source_description" text,
	"table_name" varchar(100) NOT NULL,
	"schema_name" varchar(50) NOT NULL,
	"data_source_type" varchar(20) DEFAULT 'measure-based' NOT NULL,
	"database_type" varchar(50) DEFAULT 'postgresql',
	"connection_config" jsonb,
	"is_active" boolean DEFAULT true,
	"requires_auth" boolean DEFAULT true,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"created_by" uuid
);
--> statement-breakpoint
CREATE TABLE "chart_definitions" (
	"chart_definition_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"chart_name" varchar(255) NOT NULL,
	"chart_description" text,
	"chart_type" varchar(50) NOT NULL,
	"data_source" jsonb NOT NULL,
	"chart_config" jsonb NOT NULL,
	"access_control" jsonb,
	"data_source_id" integer,
	"chart_category_id" integer,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"is_active" boolean DEFAULT true,
	"drill_down_enabled" boolean DEFAULT false,
	"drill_down_type" text,
	"drill_down_target_chart_id" uuid,
	"drill_down_button_label" text DEFAULT 'Drill Down'
);
--> statement-breakpoint
CREATE TABLE "chart_display_configurations" (
	"display_configuration_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chart_display_configurations_display_configuration_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"chart_type" varchar(50) NOT NULL,
	"frequency" varchar(20),
	"x_axis_config" jsonb,
	"y_axis_config" jsonb,
	"default_width" integer DEFAULT 800,
	"default_height" integer DEFAULT 400,
	"padding_config" jsonb,
	"time_unit" varchar(20),
	"time_display_format" varchar(50),
	"time_tooltip_format" varchar(50),
	"show_legend" boolean DEFAULT true,
	"show_tooltips" boolean DEFAULT true,
	"enable_animation" boolean DEFAULT true,
	"default_color_palette_id" integer,
	"is_default" boolean DEFAULT false,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "chart_permissions" (
	"chart_permission_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"chart_definition_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"permission_type" varchar(20) NOT NULL,
	"granted_by_user_id" uuid NOT NULL,
	"granted_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "chart_provider_colors" (
	"provider_color_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid,
	"provider_uid" integer NOT NULL,
	"provider_name" varchar(255) NOT NULL,
	"assigned_color" varchar(7) NOT NULL,
	"color_palette_id" varchar(50) DEFAULT 'tableau20',
	"is_custom" boolean DEFAULT false,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"created_by" uuid,
	"updated_by" uuid,
	CONSTRAINT "unique_org_provider_color" UNIQUE("organization_id","provider_uid")
);
--> statement-breakpoint
CREATE TABLE "color_palettes" (
	"palette_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "color_palettes_palette_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"palette_name" varchar(100) NOT NULL,
	"palette_description" text,
	"colors" jsonb NOT NULL,
	"palette_type" varchar(50) DEFAULT 'general',
	"max_colors" integer,
	"is_colorblind_safe" boolean DEFAULT false,
	"contrast_ratio" numeric(3, 2),
	"is_default" boolean DEFAULT false,
	"is_system" boolean DEFAULT false,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"created_by" uuid
);
--> statement-breakpoint
CREATE TABLE "csrf_failure_events" (
	"event_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"timestamp" timestamp with time zone DEFAULT now() NOT NULL,
	"ip_address" varchar(45) NOT NULL,
	"user_agent" text NOT NULL,
	"pathname" varchar(500) NOT NULL,
	"reason" varchar(200) NOT NULL,
	"severity" varchar(20) NOT NULL,
	"user_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "dashboard_charts" (
	"dashboard_chart_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"dashboard_id" uuid NOT NULL,
	"chart_definition_id" uuid NOT NULL,
	"position_config" jsonb,
	"added_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "dashboards" (
	"dashboard_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"dashboard_name" varchar(255) NOT NULL,
	"dashboard_description" text,
	"layout_config" jsonb NOT NULL,
	"dashboard_category_id" integer,
	"organization_id" uuid,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"is_active" boolean DEFAULT true,
	"is_published" boolean DEFAULT false,
	"is_default" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "data_sources" (
	"data_source_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "data_sources_data_source_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"data_source_name" varchar(100) NOT NULL,
	"table_name" varchar(100) NOT NULL,
	"schema_name" varchar(50) NOT NULL,
	"data_source_description" text,
	"available_fields" jsonb,
	"sample_query" text,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "explorer_column_metadata" (
	"column_metadata_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"table_id" uuid NOT NULL,
	"column_name" text NOT NULL,
	"display_name" text,
	"description" text,
	"data_type" text NOT NULL,
	"semantic_type" text,
	"is_nullable" boolean DEFAULT true,
	"is_primary_key" boolean DEFAULT false,
	"is_foreign_key" boolean DEFAULT false,
	"foreign_key_table" text,
	"foreign_key_column" text,
	"is_org_filter" boolean DEFAULT false,
	"is_phi" boolean DEFAULT false,
	"common_values" jsonb,
	"value_format" text,
	"example_values" text[],
	"min_value" text,
	"max_value" text,
	"distinct_count" integer,
	"null_percentage" numeric(5, 2),
	"statistics_last_analyzed" timestamp with time zone,
	"statistics_analysis_status" text,
	"statistics_analysis_error" text,
	"statistics_analysis_duration_ms" integer,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "explorer_improvement_suggestions" (
	"suggestion_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"feedback_id" uuid,
	"suggestion_type" text NOT NULL,
	"target_type" text NOT NULL,
	"target_id" uuid,
	"suggested_change" jsonb NOT NULL,
	"confidence_score" numeric(3, 2),
	"status" text DEFAULT 'pending',
	"applied_at" timestamp with time zone,
	"applied_by" text,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "explorer_query_feedback" (
	"feedback_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"query_history_id" uuid NOT NULL,
	"feedback_type" text NOT NULL,
	"feedback_category" text NOT NULL,
	"severity" text NOT NULL,
	"original_sql" text NOT NULL,
	"corrected_sql" text,
	"user_explanation" text,
	"detected_issue" text,
	"affected_tables" text[],
	"affected_columns" text[],
	"resolution_status" text DEFAULT 'pending',
	"resolution_action" jsonb,
	"resolved_at" timestamp with time zone,
	"resolved_by" text,
	"similar_query_count" integer DEFAULT 0,
	"recurrence_score" numeric(5, 2),
	"created_at" timestamp with time zone DEFAULT now(),
	"created_by" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "explorer_query_history" (
	"query_history_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"natural_language_query" text NOT NULL,
	"generated_sql" text NOT NULL,
	"executed_sql" text,
	"final_sql" text,
	"status" text NOT NULL,
	"execution_time_ms" integer,
	"row_count" integer,
	"error_message" text,
	"error_details" jsonb,
	"user_id" text NOT NULL,
	"user_email" text,
	"organization_id" text,
	"model_used" text DEFAULT 'claude-3-5-sonnet',
	"model_temperature" numeric(2, 1),
	"prompt_tokens" integer,
	"completion_tokens" integer,
	"total_cost_cents" integer,
	"user_rating" integer,
	"user_feedback" text,
	"was_helpful" boolean,
	"tables_used" text[],
	"execution_plan" jsonb,
	"result_sample" jsonb,
	"created_at" timestamp with time zone DEFAULT now(),
	"metadata" jsonb,
	"was_sql_edited" boolean DEFAULT false,
	"original_generated_sql" text,
	"sql_edit_count" integer DEFAULT 0
);
--> statement-breakpoint
CREATE TABLE "explorer_query_patterns" (
	"query_pattern_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"pattern_type" text,
	"natural_language_pattern" text,
	"sql_pattern" text,
	"tables_involved" text[],
	"usage_count" integer DEFAULT 1,
	"success_rate" numeric(5, 2),
	"last_seen" timestamp with time zone DEFAULT now(),
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "explorer_saved_queries" (
	"saved_query_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"query_history_id" uuid,
	"name" text NOT NULL,
	"description" text,
	"category" text,
	"natural_language_template" text,
	"sql_template" text,
	"template_variables" jsonb,
	"tags" text[],
	"is_public" boolean DEFAULT false,
	"usage_count" integer DEFAULT 0,
	"last_used" timestamp with time zone,
	"created_by" text,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "explorer_schema_instructions" (
	"instruction_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"schema_name" text DEFAULT 'ih' NOT NULL,
	"category" text,
	"title" text NOT NULL,
	"instruction" text NOT NULL,
	"priority" integer DEFAULT 2,
	"applies_to_tables" text[],
	"example_query" text,
	"example_sql" text,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"created_by" text,
	"updated_by" text
);
--> statement-breakpoint
CREATE TABLE "explorer_table_metadata" (
	"table_metadata_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"schema_name" text DEFAULT 'ih' NOT NULL,
	"table_name" text NOT NULL,
	"display_name" text,
	"description" text,
	"row_meaning" text,
	"primary_entity" text,
	"common_filters" text[],
	"common_joins" text[],
	"tier" integer DEFAULT 3,
	"sample_questions" text[],
	"tags" text[],
	"is_active" boolean DEFAULT true,
	"is_auto_discovered" boolean DEFAULT false,
	"confidence_score" numeric(3, 2),
	"row_count_estimate" bigint,
	"last_analyzed" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"created_by" text,
	"updated_by" text
);
--> statement-breakpoint
CREATE TABLE "explorer_table_relationships" (
	"table_relationship_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"from_table_id" uuid,
	"to_table_id" uuid,
	"relationship_type" text,
	"join_condition" text NOT NULL,
	"is_common" boolean DEFAULT false,
	"confidence_score" numeric(3, 2),
	"discovered_from" text,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "login_attempts" (
	"attempt_id" varchar(255) PRIMARY KEY NOT NULL,
	"email" varchar(255) NOT NULL,
	"user_id" uuid,
	"ip_address" varchar(45) NOT NULL,
	"user_agent" text,
	"device_fingerprint" varchar(255),
	"success" boolean NOT NULL,
	"failure_reason" varchar(100),
	"remember_me_requested" boolean DEFAULT false NOT NULL,
	"session_id" varchar(255),
	"attempted_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "oidc_nonces" (
	"nonce" varchar(255) PRIMARY KEY NOT NULL,
	"state" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "oidc_states" (
	"state" varchar(255) PRIMARY KEY NOT NULL,
	"nonce" varchar(255) NOT NULL,
	"user_fingerprint" varchar(64),
	"is_used" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"used_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "organizations" (
	"organization_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(255) NOT NULL,
	"slug" varchar(100) NOT NULL,
	"parent_organization_id" uuid,
	"practice_uids" integer[] DEFAULT '{}',
	"is_active" boolean DEFAULT true,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"deleted_at" timestamp with time zone,
	CONSTRAINT "organizations_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "permissions" (
	"permission_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(100) NOT NULL,
	"description" text,
	"resource" varchar(50) NOT NULL,
	"action" varchar(50) NOT NULL,
	"scope" varchar(50) DEFAULT 'own',
	"is_active" boolean DEFAULT true,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "permissions_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "practice_attributes" (
	"practice_attribute_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"practice_id" uuid,
	"phone" varchar(20),
	"email" varchar(255),
	"address_line1" varchar(255),
	"address_line2" varchar(255),
	"city" varchar(100),
	"state" varchar(50),
	"zip_code" varchar(20),
	"business_hours" text,
	"services" text,
	"insurance_accepted" text,
	"conditions_treated" text,
	"about_text" text,
	"mission_statement" text,
	"welcome_message" text,
	"logo_url" varchar(500),
	"hero_image_url" varchar(500),
	"gallery_images" text,
	"meta_title" varchar(255),
	"meta_description" varchar(500),
	"primary_color" varchar(7),
	"secondary_color" varchar(7),
	"accent_color" varchar(7),
	"hero_overlay_opacity" real DEFAULT 0.1,
	"practice_slug" text,
	"ratings_feed_enabled" boolean DEFAULT false,
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "practice_comments" (
	"comment_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"practice_id" uuid NOT NULL,
	"commenter_name" varchar(255),
	"commenter_location" varchar(255),
	"comment" text NOT NULL,
	"rating" numeric NOT NULL,
	"display_order" integer DEFAULT 0,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "practice_size_buckets" (
	"bucket_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "practice_size_buckets_bucket_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"practice_uid" integer NOT NULL,
	"organization_id" uuid,
	"size_bucket" varchar(20) NOT NULL,
	"monthly_charges_avg" numeric(18, 2),
	"percentile" numeric(5, 2),
	"calculated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "practice_size_buckets_practice_uid_unique" UNIQUE("practice_uid")
);
--> statement-breakpoint
CREATE TABLE "practices" (
	"practice_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(255) NOT NULL,
	"domain" varchar(255) NOT NULL,
	"template_id" uuid,
	"status" varchar(20) DEFAULT 'pending',
	"owner_user_id" uuid,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"deleted_at" timestamp with time zone,
	CONSTRAINT "practices_domain_unique" UNIQUE("domain")
);
--> statement-breakpoint
CREATE TABLE "refresh_tokens" (
	"token_id" varchar(255) PRIMARY KEY NOT NULL,
	"user_id" uuid NOT NULL,
	"token_hash" varchar(64) NOT NULL,
	"device_fingerprint" varchar(255) NOT NULL,
	"ip_address" varchar(45) NOT NULL,
	"user_agent" text,
	"remember_me" boolean DEFAULT false NOT NULL,
	"issued_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"last_used" timestamp with time zone DEFAULT now() NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"revoked_at" timestamp with time zone,
	"revoked_reason" varchar(50),
	"rotation_count" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "report_card_measures" (
	"measure_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "report_card_measures_measure_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"measure_name" varchar(100) NOT NULL,
	"display_name" varchar(100) NOT NULL,
	"weight" numeric(3, 1) DEFAULT '5.0',
	"is_active" boolean DEFAULT true,
	"higher_is_better" boolean DEFAULT true,
	"format_type" varchar(20) DEFAULT 'number',
	"data_source_id" integer,
	"value_column" varchar(100) DEFAULT 'numeric_value',
	"filter_criteria" jsonb DEFAULT '{}'::jsonb,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "report_card_measures_measure_name_unique" UNIQUE("measure_name")
);
--> statement-breakpoint
CREATE TABLE "report_card_results" (
	"result_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"practice_uid" integer NOT NULL,
	"organization_id" uuid,
	"report_card_month" date NOT NULL,
	"generated_at" timestamp with time zone DEFAULT now(),
	"overall_score" numeric(5, 2),
	"size_bucket" varchar(20),
	"percentile_rank" numeric(5, 2),
	"insights" jsonb,
	"measure_scores" jsonb,
	CONSTRAINT "uq_report_card_practice_month" UNIQUE("practice_uid","report_card_month")
);
--> statement-breakpoint
CREATE TABLE "report_card_statistics" (
	"statistic_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "report_card_statistics_statistic_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"practice_uid" integer NOT NULL,
	"organization_id" uuid,
	"measure_name" varchar(100) NOT NULL,
	"time_period" varchar(20) DEFAULT 'Monthly',
	"period_date" timestamp with time zone NOT NULL,
	"value" numeric(18, 2) NOT NULL,
	"collected_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "uq_report_card_statistics" UNIQUE("practice_uid","measure_name","time_period","period_date")
);
--> statement-breakpoint
CREATE TABLE "report_card_trends" (
	"trend_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "report_card_trends_trend_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"practice_uid" integer NOT NULL,
	"organization_id" uuid,
	"measure_name" varchar(100) NOT NULL,
	"trend_period" varchar(20) NOT NULL,
	"trend_direction" varchar(20) NOT NULL,
	"trend_percentage" numeric(8, 2),
	"calculated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "uq_report_card_trends" UNIQUE("practice_uid","measure_name","trend_period")
);
--> statement-breakpoint
CREATE TABLE "role_permissions" (
	"role_permission_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"role_id" uuid NOT NULL,
	"permission_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "roles" (
	"role_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(100) NOT NULL,
	"description" text,
	"organization_id" uuid,
	"is_system_role" boolean DEFAULT false,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "saml_replay_prevention" (
	"replay_id" text PRIMARY KEY NOT NULL,
	"in_response_to" text NOT NULL,
	"user_email" text NOT NULL,
	"used_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"ip_address" text NOT NULL,
	"user_agent" text,
	"session_id" text
);
--> statement-breakpoint
CREATE TABLE "staff_members" (
	"staff_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"practice_id" uuid,
	"name" varchar(255) NOT NULL,
	"title" varchar(255),
	"credentials" varchar(255),
	"bio" text,
	"photo_url" varchar(500),
	"specialties" text,
	"education" text,
	"display_order" integer DEFAULT 0,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "templates" (
	"template_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(255) NOT NULL,
	"slug" varchar(100) NOT NULL,
	"description" text,
	"preview_image_url" varchar(500),
	"is_active" boolean DEFAULT true,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"deleted_at" timestamp with time zone,
	CONSTRAINT "templates_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "token_blacklist" (
	"jti" varchar(255) PRIMARY KEY NOT NULL,
	"user_id" uuid NOT NULL,
	"token_type" varchar(20) NOT NULL,
	"blacklisted_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"reason" varchar(50) NOT NULL,
	"blacklisted_by" uuid,
	"ip_address" varchar(45),
	"user_agent" text
);
--> statement-breakpoint
CREATE TABLE "user_chart_favorites" (
	"user_id" uuid NOT NULL,
	"chart_definition_id" uuid NOT NULL,
	"favorited_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "user_organizations" (
	"user_organization_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"organization_id" uuid NOT NULL,
	"is_active" boolean DEFAULT true,
	"joined_at" timestamp with time zone DEFAULT now(),
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "user_roles" (
	"user_role_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"role_id" uuid NOT NULL,
	"organization_id" uuid,
	"granted_by" uuid,
	"granted_at" timestamp with time zone DEFAULT now(),
	"expires_at" timestamp with time zone,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "user_sessions" (
	"session_id" varchar(255) PRIMARY KEY NOT NULL,
	"user_id" uuid NOT NULL,
	"refresh_token_id" varchar(255),
	"device_fingerprint" varchar(255) NOT NULL,
	"device_name" varchar(100),
	"ip_address" varchar(45) NOT NULL,
	"user_agent" text,
	"remember_me" boolean DEFAULT false NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"last_activity" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"ended_at" timestamp with time zone,
	"end_reason" varchar(50)
);
--> statement-breakpoint
CREATE TABLE "users" (
	"user_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" varchar(255) NOT NULL,
	"first_name" varchar(100) NOT NULL,
	"last_name" varchar(100) NOT NULL,
	"password_hash" varchar(255),
	"email_verified" boolean DEFAULT false,
	"is_active" boolean DEFAULT true,
	"provider_uid" integer,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"deleted_at" timestamp with time zone,
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "webauthn_challenges" (
	"challenge_id" varchar(255) PRIMARY KEY NOT NULL,
	"user_id" uuid NOT NULL,
	"challenge" varchar(255) NOT NULL,
	"challenge_type" varchar(20) NOT NULL,
	"ip_address" varchar(45) NOT NULL,
	"user_agent" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"used_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "webauthn_credentials" (
	"credential_id" varchar(255) PRIMARY KEY NOT NULL,
	"user_id" uuid NOT NULL,
	"public_key" text NOT NULL,
	"counter" integer DEFAULT 0 NOT NULL,
	"credential_device_type" varchar(32) NOT NULL,
	"transports" text,
	"aaguid" text,
	"credential_name" varchar(100) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_used" timestamp with time zone,
	"is_active" boolean DEFAULT true NOT NULL,
	"backed_up" boolean DEFAULT false NOT NULL,
	"registration_ip" varchar(45) NOT NULL,
	"registration_user_agent" text
);
--> statement-breakpoint
CREATE TABLE "work_item_activity" (
	"work_item_activity_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"work_item_id" uuid NOT NULL,
	"activity_type" text NOT NULL,
	"field_name" text,
	"old_value" text,
	"new_value" text,
	"description" text,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "work_item_attachments" (
	"work_item_attachment_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"work_item_id" uuid NOT NULL,
	"work_item_field_id" uuid,
	"file_name" text NOT NULL,
	"file_size" integer NOT NULL,
	"file_type" text NOT NULL,
	"s3_key" text NOT NULL,
	"s3_bucket" text NOT NULL,
	"uploaded_by" uuid NOT NULL,
	"uploaded_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "work_item_comments" (
	"work_item_comment_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"work_item_id" uuid NOT NULL,
	"parent_comment_id" uuid,
	"comment_text" text NOT NULL,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "work_item_field_values" (
	"work_item_field_value_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"work_item_id" uuid NOT NULL,
	"work_item_field_id" uuid NOT NULL,
	"field_value" jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "uq_work_item_field_values_work_item_field" UNIQUE("work_item_id","work_item_field_id")
);
--> statement-breakpoint
CREATE TABLE "work_item_fields" (
	"work_item_field_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"work_item_type_id" uuid NOT NULL,
	"field_name" varchar(100) NOT NULL,
	"field_label" varchar(255) NOT NULL,
	"field_type" varchar(50) NOT NULL,
	"field_description" text,
	"field_options" jsonb,
	"field_config" jsonb,
	"is_required_on_creation" boolean DEFAULT false NOT NULL,
	"is_required_to_complete" boolean DEFAULT false NOT NULL,
	"validation_rules" jsonb,
	"default_value" text,
	"display_order" integer DEFAULT 0 NOT NULL,
	"is_visible" boolean DEFAULT true,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "work_item_status_transitions" (
	"work_item_status_transition_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"work_item_type_id" uuid NOT NULL,
	"from_status_id" uuid NOT NULL,
	"to_status_id" uuid NOT NULL,
	"is_allowed" boolean DEFAULT true NOT NULL,
	"validation_config" jsonb,
	"action_config" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "uq_transition_type_from_to" UNIQUE("work_item_type_id","from_status_id","to_status_id")
);
--> statement-breakpoint
CREATE TABLE "work_item_statuses" (
	"work_item_status_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"work_item_type_id" uuid NOT NULL,
	"status_name" text NOT NULL,
	"status_category" text NOT NULL,
	"is_initial" boolean DEFAULT false NOT NULL,
	"is_final" boolean DEFAULT false NOT NULL,
	"color" text,
	"display_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "work_item_type_relationships" (
	"work_item_type_relationship_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"parent_type_id" uuid NOT NULL,
	"child_type_id" uuid NOT NULL,
	"relationship_name" text NOT NULL,
	"is_required" boolean DEFAULT false NOT NULL,
	"min_count" integer,
	"max_count" integer,
	"auto_create" boolean DEFAULT false NOT NULL,
	"auto_create_config" jsonb,
	"display_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "work_item_types" (
	"work_item_type_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid,
	"name" text NOT NULL,
	"description" text,
	"icon" text,
	"color" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "work_item_watchers" (
	"work_item_watcher_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"work_item_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"watch_type" text DEFAULT 'manual' NOT NULL,
	"notify_status_changes" boolean DEFAULT true NOT NULL,
	"notify_comments" boolean DEFAULT true NOT NULL,
	"notify_assignments" boolean DEFAULT true NOT NULL,
	"notify_due_date" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "uq_watchers_work_item_user" UNIQUE("work_item_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "work_items" (
	"work_item_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"work_item_type_id" uuid NOT NULL,
	"organization_id" uuid NOT NULL,
	"subject" text NOT NULL,
	"description" text,
	"status_id" uuid NOT NULL,
	"priority" text DEFAULT 'medium' NOT NULL,
	"assigned_to" uuid,
	"due_date" timestamp with time zone,
	"started_at" timestamp with time zone,
	"completed_at" timestamp with time zone,
	"parent_work_item_id" uuid,
	"root_work_item_id" uuid,
	"depth" integer DEFAULT 0 NOT NULL,
	"path" text,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "account_security" ADD CONSTRAINT "account_security_user_id_users_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "announcement_reads" ADD CONSTRAINT "announcement_reads_announcement_id_announcements_announcement_id_fk" FOREIGN KEY ("announcement_id") REFERENCES "public"."announcements"("announcement_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "announcement_reads" ADD CONSTRAINT "announcement_reads_user_id_users_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "announcement_recipients" ADD CONSTRAINT "announcement_recipients_announcement_id_announcements_announcement_id_fk" FOREIGN KEY ("announcement_id") REFERENCES "public"."announcements"("announcement_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "announcement_recipients" ADD CONSTRAINT "announcement_recipients_user_id_users_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "announcements" ADD CONSTRAINT "announcements_created_by_users_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chart_data_source_columns" ADD CONSTRAINT "chart_data_source_columns_data_source_id_chart_data_sources_data_source_id_fk" FOREIGN KEY ("data_source_id") REFERENCES "public"."chart_data_sources"("data_source_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chart_definitions" ADD CONSTRAINT "chart_definitions_data_source_id_chart_data_sources_data_source_id_fk" FOREIGN KEY ("data_source_id") REFERENCES "public"."chart_data_sources"("data_source_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chart_definitions" ADD CONSTRAINT "chart_definitions_chart_category_id_chart_categories_chart_category_id_fk" FOREIGN KEY ("chart_category_id") REFERENCES "public"."chart_categories"("chart_category_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chart_definitions" ADD CONSTRAINT "chart_definitions_created_by_users_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chart_definitions" ADD CONSTRAINT "chart_definitions_drill_down_target_chart_id_chart_definitions_chart_definition_id_fk" FOREIGN KEY ("drill_down_target_chart_id") REFERENCES "public"."chart_definitions"("chart_definition_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chart_display_configurations" ADD CONSTRAINT "chart_display_configurations_default_color_palette_id_color_palettes_palette_id_fk" FOREIGN KEY ("default_color_palette_id") REFERENCES "public"."color_palettes"("palette_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chart_permissions" ADD CONSTRAINT "chart_permissions_chart_definition_id_chart_definitions_chart_definition_id_fk" FOREIGN KEY ("chart_definition_id") REFERENCES "public"."chart_definitions"("chart_definition_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chart_permissions" ADD CONSTRAINT "chart_permissions_user_id_users_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chart_permissions" ADD CONSTRAINT "chart_permissions_granted_by_user_id_users_user_id_fk" FOREIGN KEY ("granted_by_user_id") REFERENCES "public"."users"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "csrf_failure_events" ADD CONSTRAINT "csrf_failure_events_user_id_users_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dashboard_charts" ADD CONSTRAINT "dashboard_charts_dashboard_id_dashboards_dashboard_id_fk" FOREIGN KEY ("dashboard_id") REFERENCES "public"."dashboards"("dashboard_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dashboard_charts" ADD CONSTRAINT "dashboard_charts_chart_definition_id_chart_definitions_chart_definition_id_fk" FOREIGN KEY ("chart_definition_id") REFERENCES "public"."chart_definitions"("chart_definition_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dashboards" ADD CONSTRAINT "dashboards_dashboard_category_id_chart_categories_chart_category_id_fk" FOREIGN KEY ("dashboard_category_id") REFERENCES "public"."chart_categories"("chart_category_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dashboards" ADD CONSTRAINT "dashboards_organization_id_organizations_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dashboards" ADD CONSTRAINT "dashboards_created_by_users_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "explorer_column_metadata" ADD CONSTRAINT "explorer_column_metadata_table_id_explorer_table_metadata_table_metadata_id_fk" FOREIGN KEY ("table_id") REFERENCES "public"."explorer_table_metadata"("table_metadata_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "explorer_improvement_suggestions" ADD CONSTRAINT "explorer_improvement_suggestions_feedback_id_explorer_query_feedback_feedback_id_fk" FOREIGN KEY ("feedback_id") REFERENCES "public"."explorer_query_feedback"("feedback_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "explorer_query_feedback" ADD CONSTRAINT "explorer_query_feedback_query_history_id_explorer_query_history_query_history_id_fk" FOREIGN KEY ("query_history_id") REFERENCES "public"."explorer_query_history"("query_history_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "explorer_saved_queries" ADD CONSTRAINT "explorer_saved_queries_query_history_id_explorer_query_history_query_history_id_fk" FOREIGN KEY ("query_history_id") REFERENCES "public"."explorer_query_history"("query_history_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "explorer_table_relationships" ADD CONSTRAINT "explorer_table_relationships_from_table_id_explorer_table_metadata_table_metadata_id_fk" FOREIGN KEY ("from_table_id") REFERENCES "public"."explorer_table_metadata"("table_metadata_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "explorer_table_relationships" ADD CONSTRAINT "explorer_table_relationships_to_table_id_explorer_table_metadata_table_metadata_id_fk" FOREIGN KEY ("to_table_id") REFERENCES "public"."explorer_table_metadata"("table_metadata_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "login_attempts" ADD CONSTRAINT "login_attempts_user_id_users_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "oidc_nonces" ADD CONSTRAINT "oidc_nonces_state_oidc_states_state_fk" FOREIGN KEY ("state") REFERENCES "public"."oidc_states"("state") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "organizations" ADD CONSTRAINT "organizations_parent_organization_id_organizations_organization_id_fk" FOREIGN KEY ("parent_organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "practice_attributes" ADD CONSTRAINT "practice_attributes_practice_id_practices_practice_id_fk" FOREIGN KEY ("practice_id") REFERENCES "public"."practices"("practice_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "practice_comments" ADD CONSTRAINT "practice_comments_practice_id_practices_practice_id_fk" FOREIGN KEY ("practice_id") REFERENCES "public"."practices"("practice_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "practice_size_buckets" ADD CONSTRAINT "practice_size_buckets_organization_id_organizations_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "practices" ADD CONSTRAINT "practices_template_id_templates_template_id_fk" FOREIGN KEY ("template_id") REFERENCES "public"."templates"("template_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "practices" ADD CONSTRAINT "practices_owner_user_id_users_user_id_fk" FOREIGN KEY ("owner_user_id") REFERENCES "public"."users"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_user_id_users_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "report_card_measures" ADD CONSTRAINT "report_card_measures_data_source_id_chart_data_sources_data_source_id_fk" FOREIGN KEY ("data_source_id") REFERENCES "public"."chart_data_sources"("data_source_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "report_card_results" ADD CONSTRAINT "report_card_results_organization_id_organizations_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "report_card_statistics" ADD CONSTRAINT "report_card_statistics_organization_id_organizations_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "report_card_trends" ADD CONSTRAINT "report_card_trends_organization_id_organizations_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_role_id_roles_role_id_fk" FOREIGN KEY ("role_id") REFERENCES "public"."roles"("role_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_permission_id_permissions_permission_id_fk" FOREIGN KEY ("permission_id") REFERENCES "public"."permissions"("permission_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "roles" ADD CONSTRAINT "roles_organization_id_organizations_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "staff_members" ADD CONSTRAINT "staff_members_practice_id_practices_practice_id_fk" FOREIGN KEY ("practice_id") REFERENCES "public"."practices"("practice_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "token_blacklist" ADD CONSTRAINT "token_blacklist_user_id_users_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_chart_favorites" ADD CONSTRAINT "user_chart_favorites_user_id_users_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_chart_favorites" ADD CONSTRAINT "user_chart_favorites_chart_definition_id_chart_definitions_chart_definition_id_fk" FOREIGN KEY ("chart_definition_id") REFERENCES "public"."chart_definitions"("chart_definition_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_organizations" ADD CONSTRAINT "user_organizations_user_id_users_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_organizations" ADD CONSTRAINT "user_organizations_organization_id_organizations_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_roles" ADD CONSTRAINT "user_roles_user_id_users_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_roles" ADD CONSTRAINT "user_roles_role_id_roles_role_id_fk" FOREIGN KEY ("role_id") REFERENCES "public"."roles"("role_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_roles" ADD CONSTRAINT "user_roles_organization_id_organizations_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_roles" ADD CONSTRAINT "user_roles_granted_by_users_user_id_fk" FOREIGN KEY ("granted_by") REFERENCES "public"."users"("user_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_sessions" ADD CONSTRAINT "user_sessions_user_id_users_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "webauthn_credentials" ADD CONSTRAINT "webauthn_credentials_user_id_users_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "work_item_activity" ADD CONSTRAINT "work_item_activity_work_item_id_work_items_work_item_id_fk" FOREIGN KEY ("work_item_id") REFERENCES "public"."work_items"("work_item_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "work_item_activity" ADD CONSTRAINT "work_item_activity_created_by_users_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "work_item_attachments" ADD CONSTRAINT "work_item_attachments_work_item_id_work_items_work_item_id_fk" FOREIGN KEY ("work_item_id") REFERENCES "public"."work_items"("work_item_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "work_item_attachments" ADD CONSTRAINT "work_item_attachments_work_item_field_id_work_item_fields_work_item_field_id_fk" FOREIGN KEY ("work_item_field_id") REFERENCES "public"."work_item_fields"("work_item_field_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "work_item_attachments" ADD CONSTRAINT "work_item_attachments_uploaded_by_users_user_id_fk" FOREIGN KEY ("uploaded_by") REFERENCES "public"."users"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "work_item_comments" ADD CONSTRAINT "work_item_comments_work_item_id_work_items_work_item_id_fk" FOREIGN KEY ("work_item_id") REFERENCES "public"."work_items"("work_item_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "work_item_comments" ADD CONSTRAINT "work_item_comments_parent_comment_id_work_item_comments_work_item_comment_id_fk" FOREIGN KEY ("parent_comment_id") REFERENCES "public"."work_item_comments"("work_item_comment_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "work_item_comments" ADD CONSTRAINT "work_item_comments_created_by_users_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "work_item_field_values" ADD CONSTRAINT "work_item_field_values_work_item_id_work_items_work_item_id_fk" FOREIGN KEY ("work_item_id") REFERENCES "public"."work_items"("work_item_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "work_item_field_values" ADD CONSTRAINT "work_item_field_values_work_item_field_id_work_item_fields_work_item_field_id_fk" FOREIGN KEY ("work_item_field_id") REFERENCES "public"."work_item_fields"("work_item_field_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "work_item_fields" ADD CONSTRAINT "work_item_fields_work_item_type_id_work_item_types_work_item_type_id_fk" FOREIGN KEY ("work_item_type_id") REFERENCES "public"."work_item_types"("work_item_type_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "work_item_fields" ADD CONSTRAINT "work_item_fields_created_by_users_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "work_item_status_transitions" ADD CONSTRAINT "work_item_status_transitions_work_item_type_id_work_item_types_work_item_type_id_fk" FOREIGN KEY ("work_item_type_id") REFERENCES "public"."work_item_types"("work_item_type_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "work_item_status_transitions" ADD CONSTRAINT "work_item_status_transitions_from_status_id_work_item_statuses_work_item_status_id_fk" FOREIGN KEY ("from_status_id") REFERENCES "public"."work_item_statuses"("work_item_status_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "work_item_status_transitions" ADD CONSTRAINT "work_item_status_transitions_to_status_id_work_item_statuses_work_item_status_id_fk" FOREIGN KEY ("to_status_id") REFERENCES "public"."work_item_statuses"("work_item_status_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "work_item_statuses" ADD CONSTRAINT "work_item_statuses_work_item_type_id_work_item_types_work_item_type_id_fk" FOREIGN KEY ("work_item_type_id") REFERENCES "public"."work_item_types"("work_item_type_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "work_item_type_relationships" ADD CONSTRAINT "work_item_type_relationships_parent_type_id_work_item_types_work_item_type_id_fk" FOREIGN KEY ("parent_type_id") REFERENCES "public"."work_item_types"("work_item_type_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "work_item_type_relationships" ADD CONSTRAINT "work_item_type_relationships_child_type_id_work_item_types_work_item_type_id_fk" FOREIGN KEY ("child_type_id") REFERENCES "public"."work_item_types"("work_item_type_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "work_item_types" ADD CONSTRAINT "work_item_types_organization_id_organizations_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "work_item_types" ADD CONSTRAINT "work_item_types_created_by_users_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "work_item_watchers" ADD CONSTRAINT "work_item_watchers_work_item_id_work_items_work_item_id_fk" FOREIGN KEY ("work_item_id") REFERENCES "public"."work_items"("work_item_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "work_item_watchers" ADD CONSTRAINT "work_item_watchers_user_id_users_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "work_items" ADD CONSTRAINT "work_items_work_item_type_id_work_item_types_work_item_type_id_fk" FOREIGN KEY ("work_item_type_id") REFERENCES "public"."work_item_types"("work_item_type_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "work_items" ADD CONSTRAINT "work_items_organization_id_organizations_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "work_items" ADD CONSTRAINT "work_items_status_id_work_item_statuses_work_item_status_id_fk" FOREIGN KEY ("status_id") REFERENCES "public"."work_item_statuses"("work_item_status_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "work_items" ADD CONSTRAINT "work_items_assigned_to_users_user_id_fk" FOREIGN KEY ("assigned_to") REFERENCES "public"."users"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "work_items" ADD CONSTRAINT "work_items_parent_work_item_id_work_items_work_item_id_fk" FOREIGN KEY ("parent_work_item_id") REFERENCES "public"."work_items"("work_item_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "work_items" ADD CONSTRAINT "work_items_root_work_item_id_work_items_work_item_id_fk" FOREIGN KEY ("root_work_item_id") REFERENCES "public"."work_items"("work_item_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "work_items" ADD CONSTRAINT "work_items_created_by_users_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_account_security_locked_until" ON "account_security" USING btree ("locked_until");--> statement-breakpoint
CREATE INDEX "idx_account_security_suspicious" ON "account_security" USING btree ("suspicious_activity_detected");--> statement-breakpoint
CREATE INDEX "idx_account_security_mfa_enabled" ON "account_security" USING btree ("mfa_enabled");--> statement-breakpoint
CREATE INDEX "idx_account_security_mfa_skips" ON "account_security" USING btree ("mfa_skips_remaining");--> statement-breakpoint
CREATE INDEX "idx_announcement_reads_announcement" ON "announcement_reads" USING btree ("announcement_id");--> statement-breakpoint
CREATE INDEX "idx_announcement_reads_user" ON "announcement_reads" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_announcement_recipients_announcement" ON "announcement_recipients" USING btree ("announcement_id");--> statement-breakpoint
CREATE INDEX "idx_announcement_recipients_user" ON "announcement_recipients" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_announcements_publish_at" ON "announcements" USING btree ("publish_at");--> statement-breakpoint
CREATE INDEX "idx_announcements_target_type" ON "announcements" USING btree ("target_type");--> statement-breakpoint
CREATE INDEX "idx_announcements_is_active" ON "announcements" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_announcements_created_at" ON "announcements" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_announcements_deleted_at" ON "announcements" USING btree ("deleted_at");--> statement-breakpoint
CREATE INDEX "idx_audit_logs_event_type" ON "audit_logs" USING btree ("event_type");--> statement-breakpoint
CREATE INDEX "idx_audit_logs_user_id" ON "audit_logs" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_audit_logs_severity" ON "audit_logs" USING btree ("severity");--> statement-breakpoint
CREATE INDEX "idx_audit_logs_created_at" ON "audit_logs" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_audit_logs_resource" ON "audit_logs" USING btree ("resource_type","resource_id");--> statement-breakpoint
CREATE INDEX "idx_chart_categories_name" ON "chart_categories" USING btree ("category_name");--> statement-breakpoint
CREATE INDEX "idx_chart_categories_parent" ON "chart_categories" USING btree ("parent_category_id");--> statement-breakpoint
CREATE INDEX "idx_chart_data_source_columns_data_source" ON "chart_data_source_columns" USING btree ("data_source_id");--> statement-breakpoint
CREATE INDEX "idx_chart_data_source_columns_flags" ON "chart_data_source_columns" USING btree ("is_filterable","is_groupable","is_measure","is_measure_type");--> statement-breakpoint
CREATE INDEX "idx_chart_data_source_columns_active" ON "chart_data_source_columns" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_chart_data_source_columns_unique" ON "chart_data_source_columns" USING btree ("data_source_id","column_name");--> statement-breakpoint
CREATE INDEX "idx_chart_data_sources_active" ON "chart_data_sources" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_chart_data_sources_table" ON "chart_data_sources" USING btree ("table_name");--> statement-breakpoint
CREATE INDEX "idx_chart_data_sources_type" ON "chart_data_sources" USING btree ("data_source_type","is_active");--> statement-breakpoint
CREATE INDEX "idx_chart_definitions_name" ON "chart_definitions" USING btree ("chart_name");--> statement-breakpoint
CREATE INDEX "idx_chart_definitions_type" ON "chart_definitions" USING btree ("chart_type");--> statement-breakpoint
CREATE INDEX "idx_chart_definitions_created_by" ON "chart_definitions" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "idx_chart_definitions_data_source" ON "chart_definitions" USING btree ("data_source_id");--> statement-breakpoint
CREATE INDEX "idx_chart_definitions_category" ON "chart_definitions" USING btree ("chart_category_id");--> statement-breakpoint
CREATE INDEX "idx_chart_definitions_active" ON "chart_definitions" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_chart_definitions_created_at" ON "chart_definitions" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_chart_display_configurations_type_freq" ON "chart_display_configurations" USING btree ("chart_type","frequency");--> statement-breakpoint
CREATE INDEX "idx_chart_display_configurations_default" ON "chart_display_configurations" USING btree ("is_default");--> statement-breakpoint
CREATE INDEX "idx_chart_display_configurations_active" ON "chart_display_configurations" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_chart_permissions_chart" ON "chart_permissions" USING btree ("chart_definition_id");--> statement-breakpoint
CREATE INDEX "idx_chart_permissions_user" ON "chart_permissions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_chart_permissions_type" ON "chart_permissions" USING btree ("permission_type");--> statement-breakpoint
CREATE INDEX "idx_provider_colors_org_provider" ON "chart_provider_colors" USING btree ("organization_id","provider_uid");--> statement-breakpoint
CREATE INDEX "idx_provider_colors_uid" ON "chart_provider_colors" USING btree ("provider_uid");--> statement-breakpoint
CREATE INDEX "idx_provider_colors_org" ON "chart_provider_colors" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_provider_colors_custom" ON "chart_provider_colors" USING btree ("is_custom");--> statement-breakpoint
CREATE INDEX "idx_color_palettes_default" ON "color_palettes" USING btree ("is_default","is_active");--> statement-breakpoint
CREATE INDEX "idx_color_palettes_type" ON "color_palettes" USING btree ("palette_type");--> statement-breakpoint
CREATE INDEX "idx_color_palettes_system" ON "color_palettes" USING btree ("is_system");--> statement-breakpoint
CREATE INDEX "idx_csrf_failures_ip_timestamp" ON "csrf_failure_events" USING btree ("ip_address","timestamp");--> statement-breakpoint
CREATE INDEX "idx_csrf_failures_timestamp" ON "csrf_failure_events" USING btree ("timestamp");--> statement-breakpoint
CREATE INDEX "idx_csrf_failures_pathname_timestamp" ON "csrf_failure_events" USING btree ("pathname","timestamp");--> statement-breakpoint
CREATE INDEX "idx_csrf_failures_severity_timestamp" ON "csrf_failure_events" USING btree ("severity","timestamp");--> statement-breakpoint
CREATE INDEX "idx_csrf_failures_user_id" ON "csrf_failure_events" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_csrf_failures_alert_detection" ON "csrf_failure_events" USING btree ("ip_address","severity","timestamp");--> statement-breakpoint
CREATE INDEX "idx_dashboard_charts_dashboard" ON "dashboard_charts" USING btree ("dashboard_id");--> statement-breakpoint
CREATE INDEX "idx_dashboard_charts_chart" ON "dashboard_charts" USING btree ("chart_definition_id");--> statement-breakpoint
CREATE INDEX "idx_dashboards_name" ON "dashboards" USING btree ("dashboard_name");--> statement-breakpoint
CREATE INDEX "idx_dashboards_created_by" ON "dashboards" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "idx_dashboards_category" ON "dashboards" USING btree ("dashboard_category_id");--> statement-breakpoint
CREATE INDEX "idx_dashboards_organization_id" ON "dashboards" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_dashboards_published_org" ON "dashboards" USING btree ("is_published","organization_id");--> statement-breakpoint
CREATE INDEX "idx_dashboards_active" ON "dashboards" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_dashboards_published" ON "dashboards" USING btree ("is_published");--> statement-breakpoint
CREATE INDEX "idx_dashboards_default" ON "dashboards" USING btree ("is_default");--> statement-breakpoint
CREATE INDEX "idx_data_sources_name" ON "data_sources" USING btree ("data_source_name");--> statement-breakpoint
CREATE INDEX "idx_data_sources_table" ON "data_sources" USING btree ("table_name");--> statement-breakpoint
CREATE INDEX "idx_data_sources_active" ON "data_sources" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_explorer_column_metadata_table" ON "explorer_column_metadata" USING btree ("table_id");--> statement-breakpoint
CREATE INDEX "idx_explorer_column_semantic" ON "explorer_column_metadata" USING btree ("semantic_type");--> statement-breakpoint
CREATE INDEX "idx_suggestions_feedback" ON "explorer_improvement_suggestions" USING btree ("feedback_id");--> statement-breakpoint
CREATE INDEX "idx_suggestions_status" ON "explorer_improvement_suggestions" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_suggestions_type" ON "explorer_improvement_suggestions" USING btree ("suggestion_type");--> statement-breakpoint
CREATE INDEX "idx_feedback_query_history" ON "explorer_query_feedback" USING btree ("query_history_id");--> statement-breakpoint
CREATE INDEX "idx_feedback_status" ON "explorer_query_feedback" USING btree ("resolution_status");--> statement-breakpoint
CREATE INDEX "idx_feedback_type" ON "explorer_query_feedback" USING btree ("feedback_type","feedback_category");--> statement-breakpoint
CREATE INDEX "idx_feedback_severity" ON "explorer_query_feedback" USING btree ("severity");--> statement-breakpoint
CREATE INDEX "idx_explorer_query_history_user" ON "explorer_query_history" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE INDEX "idx_explorer_query_history_status" ON "explorer_query_history" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_explorer_query_history_tables" ON "explorer_query_history" USING gin ("tables_used");--> statement-breakpoint
CREATE INDEX "idx_explorer_query_history_org" ON "explorer_query_history" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_explorer_patterns_type" ON "explorer_query_patterns" USING btree ("pattern_type");--> statement-breakpoint
CREATE INDEX "idx_explorer_saved_queries_category" ON "explorer_saved_queries" USING btree ("category","is_public");--> statement-breakpoint
CREATE INDEX "idx_explorer_saved_queries_created_by" ON "explorer_saved_queries" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "idx_schema_instructions_schema" ON "explorer_schema_instructions" USING btree ("schema_name","is_active");--> statement-breakpoint
CREATE INDEX "idx_schema_instructions_priority" ON "explorer_schema_instructions" USING btree ("priority","is_active");--> statement-breakpoint
CREATE INDEX "idx_explorer_table_metadata_schema_table" ON "explorer_table_metadata" USING btree ("schema_name","table_name");--> statement-breakpoint
CREATE INDEX "idx_explorer_table_metadata_tier" ON "explorer_table_metadata" USING btree ("tier","is_active");--> statement-breakpoint
CREATE INDEX "idx_login_attempts_email" ON "login_attempts" USING btree ("email");--> statement-breakpoint
CREATE INDEX "idx_login_attempts_ip" ON "login_attempts" USING btree ("ip_address");--> statement-breakpoint
CREATE INDEX "idx_login_attempts_attempted_at" ON "login_attempts" USING btree ("attempted_at");--> statement-breakpoint
CREATE INDEX "idx_login_attempts_success" ON "login_attempts" USING btree ("success");--> statement-breakpoint
CREATE INDEX "idx_login_attempts_user_id" ON "login_attempts" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_login_attempts_session_id" ON "login_attempts" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "idx_oidc_nonces_expires" ON "oidc_nonces" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "idx_oidc_nonces_state" ON "oidc_nonces" USING btree ("state");--> statement-breakpoint
CREATE INDEX "idx_oidc_states_expires" ON "oidc_states" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "idx_oidc_states_is_used" ON "oidc_states" USING btree ("is_used");--> statement-breakpoint
CREATE INDEX "idx_organizations_slug" ON "organizations" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "idx_organizations_parent" ON "organizations" USING btree ("parent_organization_id");--> statement-breakpoint
CREATE INDEX "idx_organizations_active" ON "organizations" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_organizations_practice_uids" ON "organizations" USING gin ("practice_uids");--> statement-breakpoint
CREATE INDEX "idx_organizations_created_at" ON "organizations" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_organizations_deleted_at" ON "organizations" USING btree ("deleted_at");--> statement-breakpoint
CREATE INDEX "idx_permissions_name" ON "permissions" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_permissions_resource_action" ON "permissions" USING btree ("resource","action");--> statement-breakpoint
CREATE INDEX "idx_permissions_resource" ON "permissions" USING btree ("resource");--> statement-breakpoint
CREATE INDEX "idx_permissions_action" ON "permissions" USING btree ("action");--> statement-breakpoint
CREATE INDEX "idx_permissions_scope" ON "permissions" USING btree ("scope");--> statement-breakpoint
CREATE INDEX "idx_permissions_active" ON "permissions" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_practice_attributes_practice_id" ON "practice_attributes" USING btree ("practice_id");--> statement-breakpoint
CREATE INDEX "idx_practice_attributes_slug" ON "practice_attributes" USING btree ("practice_slug");--> statement-breakpoint
CREATE INDEX "idx_practice_comments_practice_id" ON "practice_comments" USING btree ("practice_id");--> statement-breakpoint
CREATE INDEX "idx_practice_comments_display_order" ON "practice_comments" USING btree ("practice_id","display_order");--> statement-breakpoint
CREATE INDEX "idx_practice_size_buckets_bucket" ON "practice_size_buckets" USING btree ("size_bucket");--> statement-breakpoint
CREATE INDEX "idx_practice_size_buckets_org" ON "practice_size_buckets" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_practices_domain" ON "practices" USING btree ("domain");--> statement-breakpoint
CREATE INDEX "idx_practices_template_id" ON "practices" USING btree ("template_id");--> statement-breakpoint
CREATE INDEX "idx_practices_owner" ON "practices" USING btree ("owner_user_id");--> statement-breakpoint
CREATE INDEX "idx_practices_status" ON "practices" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_refresh_tokens_user_id" ON "refresh_tokens" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_refresh_tokens_active" ON "refresh_tokens" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_refresh_tokens_expires_at" ON "refresh_tokens" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "idx_refresh_tokens_device" ON "refresh_tokens" USING btree ("device_fingerprint");--> statement-breakpoint
CREATE INDEX "idx_refresh_tokens_hash" ON "refresh_tokens" USING btree ("token_hash");--> statement-breakpoint
CREATE INDEX "idx_report_card_measures_active" ON "report_card_measures" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_report_card_measures_name" ON "report_card_measures" USING btree ("measure_name");--> statement-breakpoint
CREATE INDEX "idx_report_card_measures_data_source" ON "report_card_measures" USING btree ("data_source_id");--> statement-breakpoint
CREATE INDEX "idx_report_card_results_practice" ON "report_card_results" USING btree ("practice_uid");--> statement-breakpoint
CREATE INDEX "idx_report_card_results_generated" ON "report_card_results" USING btree ("generated_at");--> statement-breakpoint
CREATE INDEX "idx_report_card_results_bucket" ON "report_card_results" USING btree ("size_bucket");--> statement-breakpoint
CREATE INDEX "idx_report_card_results_org" ON "report_card_results" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_report_card_results_month" ON "report_card_results" USING btree ("report_card_month");--> statement-breakpoint
CREATE INDEX "idx_report_card_results_practice_month" ON "report_card_results" USING btree ("practice_uid","report_card_month");--> statement-breakpoint
CREATE INDEX "idx_report_card_statistics_practice" ON "report_card_statistics" USING btree ("practice_uid");--> statement-breakpoint
CREATE INDEX "idx_report_card_statistics_measure" ON "report_card_statistics" USING btree ("measure_name");--> statement-breakpoint
CREATE INDEX "idx_report_card_statistics_period" ON "report_card_statistics" USING btree ("period_date");--> statement-breakpoint
CREATE INDEX "idx_report_card_statistics_org" ON "report_card_statistics" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_report_card_trends_practice" ON "report_card_trends" USING btree ("practice_uid");--> statement-breakpoint
CREATE INDEX "idx_report_card_trends_period" ON "report_card_trends" USING btree ("trend_period");--> statement-breakpoint
CREATE INDEX "idx_report_card_trends_measure" ON "report_card_trends" USING btree ("measure_name");--> statement-breakpoint
CREATE INDEX "idx_report_card_trends_org" ON "report_card_trends" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_role_permissions_role" ON "role_permissions" USING btree ("role_id");--> statement-breakpoint
CREATE INDEX "idx_role_permissions_permission" ON "role_permissions" USING btree ("permission_id");--> statement-breakpoint
CREATE INDEX "idx_unique_role_permission" ON "role_permissions" USING btree ("role_id","permission_id");--> statement-breakpoint
CREATE INDEX "idx_roles_name" ON "roles" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_roles_organization" ON "roles" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_roles_system" ON "roles" USING btree ("is_system_role");--> statement-breakpoint
CREATE INDEX "idx_roles_active" ON "roles" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_roles_created_at" ON "roles" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_roles_deleted_at" ON "roles" USING btree ("deleted_at");--> statement-breakpoint
CREATE INDEX "idx_unique_role_per_org" ON "roles" USING btree ("name","organization_id");--> statement-breakpoint
CREATE INDEX "idx_saml_replay_expires_at" ON "saml_replay_prevention" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "idx_saml_replay_in_response_to" ON "saml_replay_prevention" USING btree ("in_response_to");--> statement-breakpoint
CREATE INDEX "idx_saml_replay_user_email" ON "saml_replay_prevention" USING btree ("user_email");--> statement-breakpoint
CREATE INDEX "idx_staff_members_practice_id" ON "staff_members" USING btree ("practice_id");--> statement-breakpoint
CREATE INDEX "idx_staff_members_display_order" ON "staff_members" USING btree ("practice_id","display_order");--> statement-breakpoint
CREATE INDEX "idx_staff_members_active" ON "staff_members" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_templates_slug" ON "templates" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "idx_templates_active" ON "templates" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_token_blacklist_user_id" ON "token_blacklist" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_token_blacklist_expires_at" ON "token_blacklist" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "idx_token_blacklist_type" ON "token_blacklist" USING btree ("token_type");--> statement-breakpoint
CREATE INDEX "idx_token_blacklist_blacklisted_at" ON "token_blacklist" USING btree ("blacklisted_at");--> statement-breakpoint
CREATE INDEX "pk_user_chart_favorites" ON "user_chart_favorites" USING btree ("user_id","chart_definition_id");--> statement-breakpoint
CREATE INDEX "idx_user_chart_favorites_user" ON "user_chart_favorites" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_user_chart_favorites_chart" ON "user_chart_favorites" USING btree ("chart_definition_id");--> statement-breakpoint
CREATE INDEX "idx_user_organizations_user" ON "user_organizations" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_user_organizations_org" ON "user_organizations" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_user_organizations_active" ON "user_organizations" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_user_organizations_joined_at" ON "user_organizations" USING btree ("joined_at");--> statement-breakpoint
CREATE INDEX "idx_unique_user_organization" ON "user_organizations" USING btree ("user_id","organization_id");--> statement-breakpoint
CREATE INDEX "idx_user_roles_user" ON "user_roles" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_user_roles_role" ON "user_roles" USING btree ("role_id");--> statement-breakpoint
CREATE INDEX "idx_user_roles_organization" ON "user_roles" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_user_roles_granted_by" ON "user_roles" USING btree ("granted_by");--> statement-breakpoint
CREATE INDEX "idx_user_roles_active" ON "user_roles" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_user_roles_expires_at" ON "user_roles" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "idx_unique_user_role_org" ON "user_roles" USING btree ("user_id","role_id","organization_id");--> statement-breakpoint
CREATE INDEX "idx_user_sessions_user_id" ON "user_sessions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_user_sessions_refresh_token" ON "user_sessions" USING btree ("refresh_token_id");--> statement-breakpoint
CREATE INDEX "idx_user_sessions_active" ON "user_sessions" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_user_sessions_device" ON "user_sessions" USING btree ("device_fingerprint");--> statement-breakpoint
CREATE INDEX "idx_user_sessions_last_activity" ON "user_sessions" USING btree ("last_activity");--> statement-breakpoint
CREATE INDEX "idx_users_email" ON "users" USING btree ("email");--> statement-breakpoint
CREATE INDEX "idx_users_created_at" ON "users" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_users_deleted_at" ON "users" USING btree ("deleted_at");--> statement-breakpoint
CREATE INDEX "idx_users_provider_uid" ON "users" USING btree ("provider_uid") WHERE provider_uid IS NOT NULL;--> statement-breakpoint
CREATE INDEX "idx_webauthn_challenges_user_id" ON "webauthn_challenges" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_webauthn_challenges_expires_at" ON "webauthn_challenges" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "idx_webauthn_challenges_challenge_type" ON "webauthn_challenges" USING btree ("challenge_type");--> statement-breakpoint
CREATE INDEX "idx_webauthn_challenges_expires_used" ON "webauthn_challenges" USING btree ("expires_at","used_at");--> statement-breakpoint
CREATE INDEX "idx_webauthn_credentials_user_id" ON "webauthn_credentials" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_webauthn_credentials_active" ON "webauthn_credentials" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_webauthn_credentials_last_used" ON "webauthn_credentials" USING btree ("last_used");--> statement-breakpoint
CREATE INDEX "idx_webauthn_credentials_user_active" ON "webauthn_credentials" USING btree ("user_id","is_active");--> statement-breakpoint
CREATE INDEX "idx_activity_work_item" ON "work_item_activity" USING btree ("work_item_id");--> statement-breakpoint
CREATE INDEX "idx_activity_type" ON "work_item_activity" USING btree ("activity_type");--> statement-breakpoint
CREATE INDEX "idx_activity_created_by" ON "work_item_activity" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "idx_activity_created_at" ON "work_item_activity" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_attachments_work_item" ON "work_item_attachments" USING btree ("work_item_id");--> statement-breakpoint
CREATE INDEX "idx_attachments_uploaded_by" ON "work_item_attachments" USING btree ("uploaded_by");--> statement-breakpoint
CREATE INDEX "idx_attachments_uploaded_at" ON "work_item_attachments" USING btree ("uploaded_at");--> statement-breakpoint
CREATE INDEX "idx_attachments_deleted_at" ON "work_item_attachments" USING btree ("deleted_at");--> statement-breakpoint
CREATE INDEX "idx_attachments_field" ON "work_item_attachments" USING btree ("work_item_field_id");--> statement-breakpoint
CREATE INDEX "idx_attachments_work_item_field" ON "work_item_attachments" USING btree ("work_item_id","work_item_field_id");--> statement-breakpoint
CREATE INDEX "idx_comments_work_item" ON "work_item_comments" USING btree ("work_item_id");--> statement-breakpoint
CREATE INDEX "idx_comments_parent" ON "work_item_comments" USING btree ("parent_comment_id");--> statement-breakpoint
CREATE INDEX "idx_comments_created_by" ON "work_item_comments" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "idx_comments_created_at" ON "work_item_comments" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_comments_deleted_at" ON "work_item_comments" USING btree ("deleted_at");--> statement-breakpoint
CREATE INDEX "idx_work_item_field_values_work_item" ON "work_item_field_values" USING btree ("work_item_id");--> statement-breakpoint
CREATE INDEX "idx_work_item_field_values_field" ON "work_item_field_values" USING btree ("work_item_field_id");--> statement-breakpoint
CREATE INDEX "idx_work_item_fields_type" ON "work_item_fields" USING btree ("work_item_type_id");--> statement-breakpoint
CREATE INDEX "idx_work_item_fields_created_by" ON "work_item_fields" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "idx_work_item_fields_deleted_at" ON "work_item_fields" USING btree ("deleted_at");--> statement-breakpoint
CREATE INDEX "idx_work_item_fields_display_order" ON "work_item_fields" USING btree ("display_order");--> statement-breakpoint
CREATE INDEX "idx_work_item_fields_type_visible" ON "work_item_fields" USING btree ("work_item_type_id","is_visible");--> statement-breakpoint
CREATE INDEX "idx_work_item_fields_type_order" ON "work_item_fields" USING btree ("work_item_type_id","display_order");--> statement-breakpoint
CREATE INDEX "idx_transitions_type" ON "work_item_status_transitions" USING btree ("work_item_type_id");--> statement-breakpoint
CREATE INDEX "idx_transitions_from" ON "work_item_status_transitions" USING btree ("from_status_id");--> statement-breakpoint
CREATE INDEX "idx_transitions_to" ON "work_item_status_transitions" USING btree ("to_status_id");--> statement-breakpoint
CREATE INDEX "idx_statuses_type" ON "work_item_statuses" USING btree ("work_item_type_id");--> statement-breakpoint
CREATE INDEX "idx_statuses_category" ON "work_item_statuses" USING btree ("status_category");--> statement-breakpoint
CREATE INDEX "idx_type_relationships_parent" ON "work_item_type_relationships" USING btree ("parent_type_id");--> statement-breakpoint
CREATE INDEX "idx_type_relationships_child" ON "work_item_type_relationships" USING btree ("child_type_id");--> statement-breakpoint
CREATE INDEX "idx_type_relationships_deleted_at" ON "work_item_type_relationships" USING btree ("deleted_at");--> statement-breakpoint
CREATE INDEX "idx_unique_type_relationship" ON "work_item_type_relationships" USING btree ("parent_type_id","child_type_id","deleted_at");--> statement-breakpoint
CREATE INDEX "idx_work_item_types_org" ON "work_item_types" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_work_item_types_active" ON "work_item_types" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_work_item_types_deleted_at" ON "work_item_types" USING btree ("deleted_at");--> statement-breakpoint
CREATE INDEX "idx_watchers_work_item" ON "work_item_watchers" USING btree ("work_item_id");--> statement-breakpoint
CREATE INDEX "idx_watchers_user" ON "work_item_watchers" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_watchers_type" ON "work_item_watchers" USING btree ("watch_type");--> statement-breakpoint
CREATE INDEX "idx_work_items_type" ON "work_items" USING btree ("work_item_type_id");--> statement-breakpoint
CREATE INDEX "idx_work_items_org" ON "work_items" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_work_items_status" ON "work_items" USING btree ("status_id");--> statement-breakpoint
CREATE INDEX "idx_work_items_org_status" ON "work_items" USING btree ("organization_id","status_id");--> statement-breakpoint
CREATE INDEX "idx_work_items_assigned" ON "work_items" USING btree ("assigned_to");--> statement-breakpoint
CREATE INDEX "idx_work_items_priority" ON "work_items" USING btree ("priority");--> statement-breakpoint
CREATE INDEX "idx_work_items_due_date" ON "work_items" USING btree ("due_date");--> statement-breakpoint
CREATE INDEX "idx_work_items_created_at" ON "work_items" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_work_items_created_by" ON "work_items" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "idx_work_items_deleted_at" ON "work_items" USING btree ("deleted_at");--> statement-breakpoint
CREATE INDEX "idx_work_items_parent" ON "work_items" USING btree ("parent_work_item_id");--> statement-breakpoint
CREATE INDEX "idx_work_items_root" ON "work_items" USING btree ("root_work_item_id");--> statement-breakpoint
CREATE INDEX "idx_work_items_depth" ON "work_items" USING btree ("depth");--> statement-breakpoint
CREATE INDEX "idx_work_items_path" ON "work_items" USING btree ("path");