-- Migration: Add unique constraints to work item tables
-- Generated by: drizzle-kit generate
-- Modified for: Full idempotency across all environments
-- Description:
--   1. Sync Report Card tables (may already exist in some environments)
--   2. Add drill-down columns to chart_definitions (may already exist)
--   3. Add unique constraints to work_item_field_values and work_item_watchers
-- All statements are idempotent for safe reruns

-- ============================================================================
-- Report Card Tables (CREATE TABLE IF NOT EXISTS for idempotency)
-- ============================================================================

CREATE TABLE IF NOT EXISTS "practice_size_buckets" (
	"bucket_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "practice_size_buckets_bucket_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"practice_uid" integer NOT NULL,
	"organization_id" uuid,
	"size_bucket" varchar(20) NOT NULL,
	"monthly_charges_avg" numeric(18, 2),
	"percentile" numeric(5, 2),
	"calculated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "practice_size_buckets_practice_uid_unique" UNIQUE("practice_uid")
);

CREATE TABLE IF NOT EXISTS "report_card_measures" (
	"measure_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "report_card_measures_measure_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"measure_name" varchar(100) NOT NULL,
	"display_name" varchar(100) NOT NULL,
	"weight" numeric(3, 1) DEFAULT '5.0',
	"is_active" boolean DEFAULT true,
	"higher_is_better" boolean DEFAULT true,
	"format_type" varchar(20) DEFAULT 'number',
	"data_source_id" integer,
	"value_column" varchar(100) DEFAULT 'numeric_value',
	"filter_criteria" jsonb DEFAULT '{}'::jsonb,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "report_card_measures_measure_name_unique" UNIQUE("measure_name")
);

CREATE TABLE IF NOT EXISTS "report_card_results" (
	"result_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"practice_uid" integer NOT NULL,
	"organization_id" uuid,
	"report_card_month" date NOT NULL,
	"generated_at" timestamp with time zone DEFAULT now(),
	"overall_score" numeric(5, 2),
	"size_bucket" varchar(20),
	"percentile_rank" numeric(5, 2),
	"insights" jsonb,
	"measure_scores" jsonb,
	CONSTRAINT "uq_report_card_practice_month" UNIQUE("practice_uid","report_card_month")
);

CREATE TABLE IF NOT EXISTS "report_card_statistics" (
	"statistic_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "report_card_statistics_statistic_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"practice_uid" integer NOT NULL,
	"organization_id" uuid,
	"measure_name" varchar(100) NOT NULL,
	"time_period" varchar(20) DEFAULT 'Monthly',
	"period_date" timestamp with time zone NOT NULL,
	"value" numeric(18, 2) NOT NULL,
	"collected_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "uq_report_card_statistics" UNIQUE("practice_uid","measure_name","time_period","period_date")
);

CREATE TABLE IF NOT EXISTS "report_card_trends" (
	"trend_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "report_card_trends_trend_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"practice_uid" integer NOT NULL,
	"organization_id" uuid,
	"measure_name" varchar(100) NOT NULL,
	"trend_period" varchar(20) NOT NULL,
	"trend_direction" varchar(20) NOT NULL,
	"trend_percentage" numeric(8, 2),
	"calculated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "uq_report_card_trends" UNIQUE("practice_uid","measure_name","trend_period")
);

-- ============================================================================
-- Drop old non-unique indexes (idempotent)
-- ============================================================================

DROP INDEX IF EXISTS "idx_work_item_field_values_work_item_field";
DROP INDEX IF EXISTS "idx_unique_transition";
DROP INDEX IF EXISTS "idx_unique_watcher";

-- ============================================================================
-- Chart definitions columns (add if not exists)
-- ============================================================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'chart_provider_colors' AND column_name = 'color_palette_id'
  ) THEN
    NULL; -- Column doesn't exist, but we're just setting default so skip
  ELSE
    ALTER TABLE "chart_provider_colors" ALTER COLUMN "color_palette_id" SET DEFAULT 'tableau20';
  END IF;
END $$;

ALTER TABLE "chart_definitions" ADD COLUMN IF NOT EXISTS "drill_down_enabled" boolean DEFAULT false;
ALTER TABLE "chart_definitions" ADD COLUMN IF NOT EXISTS "drill_down_type" text;
ALTER TABLE "chart_definitions" ADD COLUMN IF NOT EXISTS "drill_down_target_chart_id" uuid;
ALTER TABLE "chart_definitions" ADD COLUMN IF NOT EXISTS "drill_down_button_label" text DEFAULT 'Drill Down';

-- ============================================================================
-- Report Card Foreign Keys (idempotent)
-- ============================================================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'practice_size_buckets_organization_id_organizations_organization_id_fk'
  ) THEN
    ALTER TABLE "practice_size_buckets" ADD CONSTRAINT "practice_size_buckets_organization_id_organizations_organization_id_fk"
      FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE set null ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'report_card_measures_data_source_id_chart_data_sources_data_source_id_fk'
  ) THEN
    ALTER TABLE "report_card_measures" ADD CONSTRAINT "report_card_measures_data_source_id_chart_data_sources_data_source_id_fk"
      FOREIGN KEY ("data_source_id") REFERENCES "public"."chart_data_sources"("data_source_id") ON DELETE set null ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'report_card_results_organization_id_organizations_organization_id_fk'
  ) THEN
    ALTER TABLE "report_card_results" ADD CONSTRAINT "report_card_results_organization_id_organizations_organization_id_fk"
      FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE set null ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'report_card_statistics_organization_id_organizations_organization_id_fk'
  ) THEN
    ALTER TABLE "report_card_statistics" ADD CONSTRAINT "report_card_statistics_organization_id_organizations_organization_id_fk"
      FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE set null ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'report_card_trends_organization_id_organizations_organization_id_fk'
  ) THEN
    ALTER TABLE "report_card_trends" ADD CONSTRAINT "report_card_trends_organization_id_organizations_organization_id_fk"
      FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE set null ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

-- ============================================================================
-- Report Card Indexes (idempotent)
-- ============================================================================

CREATE INDEX IF NOT EXISTS "idx_practice_size_buckets_bucket" ON "practice_size_buckets" USING btree ("size_bucket");
CREATE INDEX IF NOT EXISTS "idx_practice_size_buckets_org" ON "practice_size_buckets" USING btree ("organization_id");
CREATE INDEX IF NOT EXISTS "idx_report_card_measures_active" ON "report_card_measures" USING btree ("is_active");
CREATE INDEX IF NOT EXISTS "idx_report_card_measures_name" ON "report_card_measures" USING btree ("measure_name");
CREATE INDEX IF NOT EXISTS "idx_report_card_measures_data_source" ON "report_card_measures" USING btree ("data_source_id");
CREATE INDEX IF NOT EXISTS "idx_report_card_results_practice" ON "report_card_results" USING btree ("practice_uid");
CREATE INDEX IF NOT EXISTS "idx_report_card_results_generated" ON "report_card_results" USING btree ("generated_at");
CREATE INDEX IF NOT EXISTS "idx_report_card_results_bucket" ON "report_card_results" USING btree ("size_bucket");
CREATE INDEX IF NOT EXISTS "idx_report_card_results_org" ON "report_card_results" USING btree ("organization_id");
CREATE INDEX IF NOT EXISTS "idx_report_card_results_month" ON "report_card_results" USING btree ("report_card_month");
CREATE INDEX IF NOT EXISTS "idx_report_card_results_practice_month" ON "report_card_results" USING btree ("practice_uid","report_card_month");
CREATE INDEX IF NOT EXISTS "idx_report_card_statistics_practice" ON "report_card_statistics" USING btree ("practice_uid");
CREATE INDEX IF NOT EXISTS "idx_report_card_statistics_measure" ON "report_card_statistics" USING btree ("measure_name");
CREATE INDEX IF NOT EXISTS "idx_report_card_statistics_period" ON "report_card_statistics" USING btree ("period_date");
CREATE INDEX IF NOT EXISTS "idx_report_card_statistics_org" ON "report_card_statistics" USING btree ("organization_id");
CREATE INDEX IF NOT EXISTS "idx_report_card_trends_practice" ON "report_card_trends" USING btree ("practice_uid");
CREATE INDEX IF NOT EXISTS "idx_report_card_trends_period" ON "report_card_trends" USING btree ("trend_period");
CREATE INDEX IF NOT EXISTS "idx_report_card_trends_measure" ON "report_card_trends" USING btree ("measure_name");
CREATE INDEX IF NOT EXISTS "idx_report_card_trends_org" ON "report_card_trends" USING btree ("organization_id");

-- ============================================================================
-- Work Item Unique Constraints (idempotent) - THE KEY FIXES
-- ============================================================================

-- Add unique constraint on work_item_field_values for (work_item_id, work_item_field_id)
-- Ensures one field value per work item + field combination
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'uq_work_item_field_values_work_item_field'
  ) THEN
    ALTER TABLE "work_item_field_values" ADD CONSTRAINT "uq_work_item_field_values_work_item_field"
      UNIQUE ("work_item_id", "work_item_field_id");
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

-- Add unique constraint on work_item_status_transitions for type+from+to
-- Ensures one transition rule per combination
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'uq_transition_type_from_to'
  ) THEN
    ALTER TABLE "work_item_status_transitions" ADD CONSTRAINT "uq_transition_type_from_to"
      UNIQUE ("work_item_type_id", "from_status_id", "to_status_id");
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

-- Add unique constraint on work_item_watchers for (work_item_id, user_id)
-- Ensures one watcher entry per work item + user combination
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'uq_watchers_work_item_user'
  ) THEN
    ALTER TABLE "work_item_watchers" ADD CONSTRAINT "uq_watchers_work_item_user"
      UNIQUE ("work_item_id", "user_id");
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;
