-- Migration: Schema Drift Sync & Missing Foreign Keys
-- Generated by: drizzle-kit generate
-- Modified for: Full idempotency across all environments
-- Description: 
--   1. Sync Report Card tables (may already exist in some environments)
--   2. Add drill-down columns to chart_definitions
--   3. Add missing work item foreign keys (were commented out in migration 0022)
--   4. Add unique constraint to work_item_status_transitions
-- All statements are idempotent for safe reruns

-- ============================================================================
-- Report Card Tables (CREATE TABLE IF NOT EXISTS for idempotency)
-- ============================================================================

CREATE TABLE IF NOT EXISTS "practice_size_buckets" (
	"bucket_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "practice_size_buckets_bucket_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"practice_uid" integer NOT NULL,
	"organization_id" uuid,
	"size_bucket" varchar(20) NOT NULL,
	"monthly_charges_avg" numeric(18, 2),
	"percentile" numeric(5, 2),
	"calculated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "practice_size_buckets_practice_uid_unique" UNIQUE("practice_uid")
);

CREATE TABLE IF NOT EXISTS "report_card_measures" (
	"measure_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "report_card_measures_measure_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"measure_name" varchar(100) NOT NULL,
	"display_name" varchar(100) NOT NULL,
	"weight" numeric(3, 1) DEFAULT '5.0',
	"is_active" boolean DEFAULT true,
	"higher_is_better" boolean DEFAULT true,
	"format_type" varchar(20) DEFAULT 'number',
	"data_source_id" integer,
	"value_column" varchar(100) DEFAULT 'numeric_value',
	"filter_criteria" jsonb DEFAULT '{}'::jsonb,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "report_card_measures_measure_name_unique" UNIQUE("measure_name")
);

CREATE TABLE IF NOT EXISTS "report_card_results" (
	"result_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"practice_uid" integer NOT NULL,
	"organization_id" uuid,
	"report_card_month" date,
	"generated_at" timestamp with time zone DEFAULT now(),
	"overall_score" numeric(5, 2),
	"size_bucket" varchar(20),
	"percentile_rank" numeric(5, 2),
	"insights" jsonb,
	"measure_scores" jsonb
);

CREATE TABLE IF NOT EXISTS "report_card_statistics" (
	"statistic_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "report_card_statistics_statistic_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"practice_uid" integer NOT NULL,
	"organization_id" uuid,
	"measure_name" varchar(100) NOT NULL,
	"time_period" varchar(20) DEFAULT 'Monthly',
	"period_date" timestamp with time zone NOT NULL,
	"value" numeric(18, 2) NOT NULL,
	"collected_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "report_card_trends" (
	"trend_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "report_card_trends_trend_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"practice_uid" integer NOT NULL,
	"organization_id" uuid,
	"measure_name" varchar(100) NOT NULL,
	"trend_period" varchar(20) NOT NULL,
	"trend_direction" varchar(20) NOT NULL,
	"trend_percentage" numeric(8, 2),
	"calculated_at" timestamp with time zone DEFAULT now()
);

-- ============================================================================
-- Report Card Columns (add if missing)
-- ============================================================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'report_card_results' AND column_name = 'report_card_month'
  ) THEN
    ALTER TABLE "report_card_results" ADD COLUMN "report_card_month" date;
  END IF;
END $$;

-- Backfill report_card_month if null
UPDATE "report_card_results"
SET "report_card_month" = DATE_TRUNC('month', generated_at)::date
WHERE "report_card_month" IS NULL AND "generated_at" IS NOT NULL;

-- ============================================================================
-- Report Card Unique Constraints (idempotent)
-- ============================================================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'uq_report_card_practice_month'
  ) THEN
    -- Only add if no duplicates exist
    IF NOT EXISTS (
      SELECT practice_uid, report_card_month, COUNT(*)
      FROM report_card_results
      WHERE report_card_month IS NOT NULL
      GROUP BY practice_uid, report_card_month
      HAVING COUNT(*) > 1
    ) THEN
      ALTER TABLE "report_card_results" ADD CONSTRAINT "uq_report_card_practice_month"
        UNIQUE("practice_uid","report_card_month");
    END IF;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'uq_report_card_statistics'
  ) THEN
    -- Only add if no duplicates exist
    IF NOT EXISTS (
      SELECT practice_uid, measure_name, time_period, period_date, COUNT(*)
      FROM report_card_statistics
      GROUP BY practice_uid, measure_name, time_period, period_date
      HAVING COUNT(*) > 1
    ) THEN
      ALTER TABLE "report_card_statistics" ADD CONSTRAINT "uq_report_card_statistics"
        UNIQUE("practice_uid","measure_name","time_period","period_date");
    END IF;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'uq_report_card_trends'
  ) THEN
    -- Only add if no duplicates exist
    IF NOT EXISTS (
      SELECT practice_uid, measure_name, trend_period, COUNT(*)
      FROM report_card_trends
      GROUP BY practice_uid, measure_name, trend_period
      HAVING COUNT(*) > 1
    ) THEN
      ALTER TABLE "report_card_trends" ADD CONSTRAINT "uq_report_card_trends"
        UNIQUE("practice_uid","measure_name","trend_period");
    END IF;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

-- ============================================================================
-- Chart Definitions Columns (idempotent)
-- ============================================================================

DROP INDEX IF EXISTS "idx_unique_transition";

DO $$
BEGIN
  ALTER TABLE "chart_provider_colors" ALTER COLUMN "color_palette_id" SET DEFAULT 'tableau20';
EXCEPTION
  WHEN undefined_column THEN NULL;
  WHEN undefined_table THEN NULL;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'chart_definitions' AND column_name = 'drill_down_enabled'
  ) THEN
    ALTER TABLE "chart_definitions" ADD COLUMN "drill_down_enabled" boolean DEFAULT false;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'chart_definitions' AND column_name = 'drill_down_type'
  ) THEN
    ALTER TABLE "chart_definitions" ADD COLUMN "drill_down_type" text;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'chart_definitions' AND column_name = 'drill_down_target_chart_id'
  ) THEN
    ALTER TABLE "chart_definitions" ADD COLUMN "drill_down_target_chart_id" uuid;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'chart_definitions' AND column_name = 'drill_down_button_label'
  ) THEN
    ALTER TABLE "chart_definitions" ADD COLUMN "drill_down_button_label" text DEFAULT 'Drill Down';
  END IF;
END $$;

-- ============================================================================
-- Report Card Foreign Keys (idempotent)
-- ============================================================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'practice_size_buckets_organization_id_organizations_organization_id_fk'
  ) THEN
    ALTER TABLE "practice_size_buckets" ADD CONSTRAINT "practice_size_buckets_organization_id_organizations_organization_id_fk"
      FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE set null ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'report_card_measures_data_source_id_chart_data_sources_data_source_id_fk'
  ) THEN
    ALTER TABLE "report_card_measures" ADD CONSTRAINT "report_card_measures_data_source_id_chart_data_sources_data_source_id_fk"
      FOREIGN KEY ("data_source_id") REFERENCES "public"."chart_data_sources"("data_source_id") ON DELETE set null ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'report_card_results_organization_id_organizations_organization_id_fk'
  ) THEN
    ALTER TABLE "report_card_results" ADD CONSTRAINT "report_card_results_organization_id_organizations_organization_id_fk"
      FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE set null ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'report_card_statistics_organization_id_organizations_organization_id_fk'
  ) THEN
    ALTER TABLE "report_card_statistics" ADD CONSTRAINT "report_card_statistics_organization_id_organizations_organization_id_fk"
      FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE set null ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'report_card_trends_organization_id_organizations_organization_id_fk'
  ) THEN
    ALTER TABLE "report_card_trends" ADD CONSTRAINT "report_card_trends_organization_id_organizations_organization_id_fk"
      FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE set null ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

-- ============================================================================
-- Report Card Indexes (idempotent)
-- ============================================================================

CREATE INDEX IF NOT EXISTS "idx_practice_size_buckets_bucket" ON "practice_size_buckets" USING btree ("size_bucket");
CREATE INDEX IF NOT EXISTS "idx_practice_size_buckets_org" ON "practice_size_buckets" USING btree ("organization_id");
CREATE INDEX IF NOT EXISTS "idx_report_card_measures_active" ON "report_card_measures" USING btree ("is_active");
CREATE INDEX IF NOT EXISTS "idx_report_card_measures_name" ON "report_card_measures" USING btree ("measure_name");
CREATE INDEX IF NOT EXISTS "idx_report_card_measures_data_source" ON "report_card_measures" USING btree ("data_source_id");
CREATE INDEX IF NOT EXISTS "idx_report_card_results_practice" ON "report_card_results" USING btree ("practice_uid");
CREATE INDEX IF NOT EXISTS "idx_report_card_results_generated" ON "report_card_results" USING btree ("generated_at");
CREATE INDEX IF NOT EXISTS "idx_report_card_results_bucket" ON "report_card_results" USING btree ("size_bucket");
CREATE INDEX IF NOT EXISTS "idx_report_card_results_org" ON "report_card_results" USING btree ("organization_id");
CREATE INDEX IF NOT EXISTS "idx_report_card_results_month" ON "report_card_results" USING btree ("report_card_month");
CREATE INDEX IF NOT EXISTS "idx_report_card_results_practice_month" ON "report_card_results" USING btree ("practice_uid","report_card_month");
CREATE INDEX IF NOT EXISTS "idx_report_card_statistics_practice" ON "report_card_statistics" USING btree ("practice_uid");
CREATE INDEX IF NOT EXISTS "idx_report_card_statistics_measure" ON "report_card_statistics" USING btree ("measure_name");
CREATE INDEX IF NOT EXISTS "idx_report_card_statistics_period" ON "report_card_statistics" USING btree ("period_date");
CREATE INDEX IF NOT EXISTS "idx_report_card_statistics_org" ON "report_card_statistics" USING btree ("organization_id");
CREATE INDEX IF NOT EXISTS "idx_report_card_trends_practice" ON "report_card_trends" USING btree ("practice_uid");
CREATE INDEX IF NOT EXISTS "idx_report_card_trends_period" ON "report_card_trends" USING btree ("trend_period");
CREATE INDEX IF NOT EXISTS "idx_report_card_trends_measure" ON "report_card_trends" USING btree ("measure_name");
CREATE INDEX IF NOT EXISTS "idx_report_card_trends_org" ON "report_card_trends" USING btree ("organization_id");

-- ============================================================================
-- Work Item Status Transitions Unique Constraint (idempotent)
-- ============================================================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'uq_transition_type_from_to'
  ) THEN
    ALTER TABLE "work_item_status_transitions" ADD CONSTRAINT "uq_transition_type_from_to"
      UNIQUE("work_item_type_id","from_status_id","to_status_id");
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

-- ============================================================================
-- WORK ITEM FOREIGN KEYS (were commented out in migration 0022)
-- These are critical for referential integrity
-- ============================================================================

-- work_item_types -> organizations
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'work_item_types_organization_id_organizations_organization_id_fk'
  ) THEN
    ALTER TABLE "work_item_types" ADD CONSTRAINT "work_item_types_organization_id_organizations_organization_id_fk"
      FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE cascade ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

-- work_item_types -> users (created_by)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'work_item_types_created_by_users_user_id_fk'
  ) THEN
    ALTER TABLE "work_item_types" ADD CONSTRAINT "work_item_types_created_by_users_user_id_fk"
      FOREIGN KEY ("created_by") REFERENCES "public"."users"("user_id") ON DELETE no action ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

-- work_item_statuses -> work_item_types
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'work_item_statuses_work_item_type_id_work_item_types_work_item_type_id_fk'
  ) THEN
    ALTER TABLE "work_item_statuses" ADD CONSTRAINT "work_item_statuses_work_item_type_id_work_item_types_work_item_type_id_fk"
      FOREIGN KEY ("work_item_type_id") REFERENCES "public"."work_item_types"("work_item_type_id") ON DELETE cascade ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

-- work_item_status_transitions -> work_item_types
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'work_item_status_transitions_work_item_type_id_work_item_types_work_item_type_id_fk'
  ) THEN
    ALTER TABLE "work_item_status_transitions" ADD CONSTRAINT "work_item_status_transitions_work_item_type_id_work_item_types_work_item_type_id_fk"
      FOREIGN KEY ("work_item_type_id") REFERENCES "public"."work_item_types"("work_item_type_id") ON DELETE cascade ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

-- work_item_status_transitions -> work_item_statuses (from_status)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'work_item_status_transitions_from_status_id_work_item_statuses_work_item_status_id_fk'
  ) THEN
    ALTER TABLE "work_item_status_transitions" ADD CONSTRAINT "work_item_status_transitions_from_status_id_work_item_statuses_work_item_status_id_fk"
      FOREIGN KEY ("from_status_id") REFERENCES "public"."work_item_statuses"("work_item_status_id") ON DELETE cascade ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

-- work_item_status_transitions -> work_item_statuses (to_status)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'work_item_status_transitions_to_status_id_work_item_statuses_work_item_status_id_fk'
  ) THEN
    ALTER TABLE "work_item_status_transitions" ADD CONSTRAINT "work_item_status_transitions_to_status_id_work_item_statuses_work_item_status_id_fk"
      FOREIGN KEY ("to_status_id") REFERENCES "public"."work_item_statuses"("work_item_status_id") ON DELETE cascade ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

-- work_item_type_relationships -> work_item_types (parent)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'work_item_type_relationships_parent_type_id_work_item_types_work_item_type_id_fk'
  ) THEN
    ALTER TABLE "work_item_type_relationships" ADD CONSTRAINT "work_item_type_relationships_parent_type_id_work_item_types_work_item_type_id_fk"
      FOREIGN KEY ("parent_type_id") REFERENCES "public"."work_item_types"("work_item_type_id") ON DELETE cascade ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

-- work_item_type_relationships -> work_item_types (child)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'work_item_type_relationships_child_type_id_work_item_types_work_item_type_id_fk'
  ) THEN
    ALTER TABLE "work_item_type_relationships" ADD CONSTRAINT "work_item_type_relationships_child_type_id_work_item_types_work_item_type_id_fk"
      FOREIGN KEY ("child_type_id") REFERENCES "public"."work_item_types"("work_item_type_id") ON DELETE cascade ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

-- work_item_fields -> work_item_types
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'work_item_fields_work_item_type_id_work_item_types_work_item_type_id_fk'
  ) THEN
    ALTER TABLE "work_item_fields" ADD CONSTRAINT "work_item_fields_work_item_type_id_work_item_types_work_item_type_id_fk"
      FOREIGN KEY ("work_item_type_id") REFERENCES "public"."work_item_types"("work_item_type_id") ON DELETE cascade ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

-- work_item_fields -> users (created_by)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'work_item_fields_created_by_users_user_id_fk'
  ) THEN
    ALTER TABLE "work_item_fields" ADD CONSTRAINT "work_item_fields_created_by_users_user_id_fk"
      FOREIGN KEY ("created_by") REFERENCES "public"."users"("user_id") ON DELETE cascade ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

-- work_item_field_values -> work_items
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'work_item_field_values_work_item_id_work_items_work_item_id_fk'
  ) THEN
    ALTER TABLE "work_item_field_values" ADD CONSTRAINT "work_item_field_values_work_item_id_work_items_work_item_id_fk"
      FOREIGN KEY ("work_item_id") REFERENCES "public"."work_items"("work_item_id") ON DELETE cascade ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

-- work_item_field_values -> work_item_fields
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'work_item_field_values_work_item_field_id_work_item_fields_work_item_field_id_fk'
  ) THEN
    ALTER TABLE "work_item_field_values" ADD CONSTRAINT "work_item_field_values_work_item_field_id_work_item_fields_work_item_field_id_fk"
      FOREIGN KEY ("work_item_field_id") REFERENCES "public"."work_item_fields"("work_item_field_id") ON DELETE cascade ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

-- work_items -> work_item_types
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'work_items_work_item_type_id_work_item_types_work_item_type_id_fk'
  ) THEN
    ALTER TABLE "work_items" ADD CONSTRAINT "work_items_work_item_type_id_work_item_types_work_item_type_id_fk"
      FOREIGN KEY ("work_item_type_id") REFERENCES "public"."work_item_types"("work_item_type_id") ON DELETE no action ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

-- work_items -> organizations
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'work_items_organization_id_organizations_organization_id_fk'
  ) THEN
    ALTER TABLE "work_items" ADD CONSTRAINT "work_items_organization_id_organizations_organization_id_fk"
      FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE cascade ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

-- work_items -> work_item_statuses (status_id)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'work_items_status_id_work_item_statuses_work_item_status_id_fk'
  ) THEN
    ALTER TABLE "work_items" ADD CONSTRAINT "work_items_status_id_work_item_statuses_work_item_status_id_fk"
      FOREIGN KEY ("status_id") REFERENCES "public"."work_item_statuses"("work_item_status_id") ON DELETE no action ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

-- work_items -> users (assigned_to)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'work_items_assigned_to_users_user_id_fk'
  ) THEN
    ALTER TABLE "work_items" ADD CONSTRAINT "work_items_assigned_to_users_user_id_fk"
      FOREIGN KEY ("assigned_to") REFERENCES "public"."users"("user_id") ON DELETE no action ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

-- work_items -> users (created_by)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'work_items_created_by_users_user_id_fk'
  ) THEN
    ALTER TABLE "work_items" ADD CONSTRAINT "work_items_created_by_users_user_id_fk"
      FOREIGN KEY ("created_by") REFERENCES "public"."users"("user_id") ON DELETE no action ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

-- work_item_activity -> work_items
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'work_item_activity_work_item_id_work_items_work_item_id_fk'
  ) THEN
    ALTER TABLE "work_item_activity" ADD CONSTRAINT "work_item_activity_work_item_id_work_items_work_item_id_fk"
      FOREIGN KEY ("work_item_id") REFERENCES "public"."work_items"("work_item_id") ON DELETE cascade ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

-- work_item_activity -> users (created_by)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'work_item_activity_created_by_users_user_id_fk'
  ) THEN
    ALTER TABLE "work_item_activity" ADD CONSTRAINT "work_item_activity_created_by_users_user_id_fk"
      FOREIGN KEY ("created_by") REFERENCES "public"."users"("user_id") ON DELETE no action ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

-- work_item_attachments -> work_items
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'work_item_attachments_work_item_id_work_items_work_item_id_fk'
  ) THEN
    ALTER TABLE "work_item_attachments" ADD CONSTRAINT "work_item_attachments_work_item_id_work_items_work_item_id_fk"
      FOREIGN KEY ("work_item_id") REFERENCES "public"."work_items"("work_item_id") ON DELETE cascade ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

-- work_item_attachments -> work_item_fields
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'work_item_attachments_work_item_field_id_work_item_fields_work_item_field_id_fk'
  ) THEN
    ALTER TABLE "work_item_attachments" ADD CONSTRAINT "work_item_attachments_work_item_field_id_work_item_fields_work_item_field_id_fk"
      FOREIGN KEY ("work_item_field_id") REFERENCES "public"."work_item_fields"("work_item_field_id") ON DELETE cascade ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

-- work_item_attachments -> users (uploaded_by)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'work_item_attachments_uploaded_by_users_user_id_fk'
  ) THEN
    ALTER TABLE "work_item_attachments" ADD CONSTRAINT "work_item_attachments_uploaded_by_users_user_id_fk"
      FOREIGN KEY ("uploaded_by") REFERENCES "public"."users"("user_id") ON DELETE no action ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

-- work_item_comments -> work_items
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'work_item_comments_work_item_id_work_items_work_item_id_fk'
  ) THEN
    ALTER TABLE "work_item_comments" ADD CONSTRAINT "work_item_comments_work_item_id_work_items_work_item_id_fk"
      FOREIGN KEY ("work_item_id") REFERENCES "public"."work_items"("work_item_id") ON DELETE cascade ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

-- work_item_comments -> users (created_by)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'work_item_comments_created_by_users_user_id_fk'
  ) THEN
    ALTER TABLE "work_item_comments" ADD CONSTRAINT "work_item_comments_created_by_users_user_id_fk"
      FOREIGN KEY ("created_by") REFERENCES "public"."users"("user_id") ON DELETE no action ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

-- work_item_watchers -> work_items
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'work_item_watchers_work_item_id_work_items_work_item_id_fk'
  ) THEN
    ALTER TABLE "work_item_watchers" ADD CONSTRAINT "work_item_watchers_work_item_id_work_items_work_item_id_fk"
      FOREIGN KEY ("work_item_id") REFERENCES "public"."work_items"("work_item_id") ON DELETE cascade ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

-- work_item_watchers -> users
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'work_item_watchers_user_id_users_user_id_fk'
  ) THEN
    ALTER TABLE "work_item_watchers" ADD CONSTRAINT "work_item_watchers_user_id_users_user_id_fk"
      FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE cascade ON UPDATE no action;
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;

-- ============================================================================
-- WORK ITEM INDEXES (were commented out in migration 0022)
-- ============================================================================

CREATE INDEX IF NOT EXISTS "idx_work_item_types_org" ON "work_item_types" USING btree ("organization_id");
CREATE INDEX IF NOT EXISTS "idx_work_item_types_active" ON "work_item_types" USING btree ("is_active");
CREATE INDEX IF NOT EXISTS "idx_work_item_types_deleted_at" ON "work_item_types" USING btree ("deleted_at");
CREATE INDEX IF NOT EXISTS "idx_statuses_type" ON "work_item_statuses" USING btree ("work_item_type_id");
CREATE INDEX IF NOT EXISTS "idx_statuses_category" ON "work_item_statuses" USING btree ("status_category");
CREATE INDEX IF NOT EXISTS "idx_transitions_type" ON "work_item_status_transitions" USING btree ("work_item_type_id");
CREATE INDEX IF NOT EXISTS "idx_transitions_from" ON "work_item_status_transitions" USING btree ("from_status_id");
CREATE INDEX IF NOT EXISTS "idx_transitions_to" ON "work_item_status_transitions" USING btree ("to_status_id");
CREATE INDEX IF NOT EXISTS "idx_type_relationships_parent" ON "work_item_type_relationships" USING btree ("parent_type_id");
CREATE INDEX IF NOT EXISTS "idx_type_relationships_child" ON "work_item_type_relationships" USING btree ("child_type_id");
CREATE INDEX IF NOT EXISTS "idx_type_relationships_deleted_at" ON "work_item_type_relationships" USING btree ("deleted_at");
CREATE INDEX IF NOT EXISTS "idx_unique_type_relationship" ON "work_item_type_relationships" USING btree ("parent_type_id","child_type_id","deleted_at");
CREATE INDEX IF NOT EXISTS "idx_work_item_fields_type" ON "work_item_fields" USING btree ("work_item_type_id");
CREATE INDEX IF NOT EXISTS "idx_work_item_fields_created_by" ON "work_item_fields" USING btree ("created_by");
CREATE INDEX IF NOT EXISTS "idx_work_item_fields_deleted_at" ON "work_item_fields" USING btree ("deleted_at");
CREATE INDEX IF NOT EXISTS "idx_work_item_fields_display_order" ON "work_item_fields" USING btree ("display_order");
CREATE INDEX IF NOT EXISTS "idx_work_item_fields_type_visible" ON "work_item_fields" USING btree ("work_item_type_id","is_visible");
CREATE INDEX IF NOT EXISTS "idx_work_item_fields_type_order" ON "work_item_fields" USING btree ("work_item_type_id","display_order");
CREATE INDEX IF NOT EXISTS "idx_work_item_field_values_work_item" ON "work_item_field_values" USING btree ("work_item_id");
CREATE INDEX IF NOT EXISTS "idx_work_item_field_values_field" ON "work_item_field_values" USING btree ("work_item_field_id");
CREATE INDEX IF NOT EXISTS "idx_work_item_field_values_work_item_field" ON "work_item_field_values" USING btree ("work_item_id","work_item_field_id");
CREATE INDEX IF NOT EXISTS "idx_work_items_type" ON "work_items" USING btree ("work_item_type_id");
CREATE INDEX IF NOT EXISTS "idx_work_items_org" ON "work_items" USING btree ("organization_id");
CREATE INDEX IF NOT EXISTS "idx_work_items_status" ON "work_items" USING btree ("status_id");
CREATE INDEX IF NOT EXISTS "idx_work_items_assigned" ON "work_items" USING btree ("assigned_to");
CREATE INDEX IF NOT EXISTS "idx_work_items_priority" ON "work_items" USING btree ("priority");
CREATE INDEX IF NOT EXISTS "idx_work_items_due_date" ON "work_items" USING btree ("due_date");
CREATE INDEX IF NOT EXISTS "idx_work_items_created_at" ON "work_items" USING btree ("created_at");
CREATE INDEX IF NOT EXISTS "idx_work_items_created_by" ON "work_items" USING btree ("created_by");
CREATE INDEX IF NOT EXISTS "idx_work_items_deleted_at" ON "work_items" USING btree ("deleted_at");
CREATE INDEX IF NOT EXISTS "idx_work_items_parent" ON "work_items" USING btree ("parent_work_item_id");
CREATE INDEX IF NOT EXISTS "idx_work_items_root" ON "work_items" USING btree ("root_work_item_id");
CREATE INDEX IF NOT EXISTS "idx_work_items_depth" ON "work_items" USING btree ("depth");
CREATE INDEX IF NOT EXISTS "idx_work_items_path" ON "work_items" USING btree ("path");
CREATE INDEX IF NOT EXISTS "idx_activity_work_item" ON "work_item_activity" USING btree ("work_item_id");
CREATE INDEX IF NOT EXISTS "idx_activity_type" ON "work_item_activity" USING btree ("activity_type");
CREATE INDEX IF NOT EXISTS "idx_activity_created_by" ON "work_item_activity" USING btree ("created_by");
CREATE INDEX IF NOT EXISTS "idx_activity_created_at" ON "work_item_activity" USING btree ("created_at");
CREATE INDEX IF NOT EXISTS "idx_attachments_work_item" ON "work_item_attachments" USING btree ("work_item_id");
CREATE INDEX IF NOT EXISTS "idx_attachments_uploaded_by" ON "work_item_attachments" USING btree ("uploaded_by");
CREATE INDEX IF NOT EXISTS "idx_attachments_uploaded_at" ON "work_item_attachments" USING btree ("uploaded_at");
CREATE INDEX IF NOT EXISTS "idx_attachments_deleted_at" ON "work_item_attachments" USING btree ("deleted_at");
CREATE INDEX IF NOT EXISTS "idx_attachments_field" ON "work_item_attachments" USING btree ("work_item_field_id");
CREATE INDEX IF NOT EXISTS "idx_attachments_work_item_field" ON "work_item_attachments" USING btree ("work_item_id","work_item_field_id");
CREATE INDEX IF NOT EXISTS "idx_comments_work_item" ON "work_item_comments" USING btree ("work_item_id");
CREATE INDEX IF NOT EXISTS "idx_comments_parent" ON "work_item_comments" USING btree ("parent_comment_id");
CREATE INDEX IF NOT EXISTS "idx_comments_created_by" ON "work_item_comments" USING btree ("created_by");
CREATE INDEX IF NOT EXISTS "idx_comments_created_at" ON "work_item_comments" USING btree ("created_at");
CREATE INDEX IF NOT EXISTS "idx_comments_deleted_at" ON "work_item_comments" USING btree ("deleted_at");
CREATE INDEX IF NOT EXISTS "idx_watchers_work_item" ON "work_item_watchers" USING btree ("work_item_id");
CREATE INDEX IF NOT EXISTS "idx_watchers_user" ON "work_item_watchers" USING btree ("user_id");
CREATE INDEX IF NOT EXISTS "idx_watchers_type" ON "work_item_watchers" USING btree ("watch_type");
CREATE INDEX IF NOT EXISTS "idx_unique_watcher" ON "work_item_watchers" USING btree ("work_item_id","user_id");
