-- Migration: Add announcements tables for user notification system
-- Note: Some statements may duplicate 0038_add_missing_fk_constraints_and_indexes.sql
-- All statements are idempotent to handle any execution order

-- ============================================================================
-- PART 1: CREATE ANNOUNCEMENT TABLES
-- ============================================================================

-- Create announcements table
DO $$
BEGIN
    CREATE TABLE "announcements" (
        "announcement_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
        "subject" text NOT NULL,
        "body" text NOT NULL,
        "target_type" text DEFAULT 'all' NOT NULL,
        "publish_at" timestamp with time zone,
        "expires_at" timestamp with time zone,
        "is_active" boolean DEFAULT true NOT NULL,
        "priority" text DEFAULT 'normal' NOT NULL,
        "created_by" uuid NOT NULL,
        "created_at" timestamp with time zone DEFAULT now() NOT NULL,
        "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
        "deleted_at" timestamp with time zone
    );
EXCEPTION
    WHEN duplicate_table THEN NULL;
END $$;

-- Create announcement_recipients table
DO $$
BEGIN
    CREATE TABLE "announcement_recipients" (
        "announcement_recipient_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
        "announcement_id" uuid NOT NULL,
        "user_id" uuid NOT NULL,
        "created_at" timestamp with time zone DEFAULT now() NOT NULL,
        CONSTRAINT "uq_announcement_recipients" UNIQUE("announcement_id","user_id")
    );
EXCEPTION
    WHEN duplicate_table THEN NULL;
END $$;

-- Create announcement_reads table
DO $$
BEGIN
    CREATE TABLE "announcement_reads" (
        "announcement_read_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
        "announcement_id" uuid NOT NULL,
        "user_id" uuid NOT NULL,
        "read_at" timestamp with time zone DEFAULT now() NOT NULL,
        CONSTRAINT "uq_announcement_reads" UNIQUE("announcement_id","user_id")
    );
EXCEPTION
    WHEN duplicate_table THEN NULL;
END $$;

-- ============================================================================
-- PART 2: CREATE REPORT CARD TABLES (if not already created by 0038)
-- ============================================================================

-- Create practice_size_buckets table
DO $$
BEGIN
    CREATE TABLE "practice_size_buckets" (
        "bucket_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "practice_size_buckets_bucket_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
        "practice_uid" integer NOT NULL,
        "organization_id" uuid,
        "size_bucket" varchar(20) NOT NULL,
        "monthly_charges_avg" numeric(18, 2),
        "percentile" numeric(5, 2),
        "calculated_at" timestamp with time zone DEFAULT now(),
        CONSTRAINT "practice_size_buckets_practice_uid_unique" UNIQUE("practice_uid")
    );
EXCEPTION
    WHEN duplicate_table THEN NULL;
END $$;

-- Create report_card_measures table
DO $$
BEGIN
    CREATE TABLE "report_card_measures" (
        "measure_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "report_card_measures_measure_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
        "measure_name" varchar(100) NOT NULL,
        "display_name" varchar(100) NOT NULL,
        "weight" numeric(3, 1) DEFAULT '5.0',
        "is_active" boolean DEFAULT true,
        "higher_is_better" boolean DEFAULT true,
        "format_type" varchar(20) DEFAULT 'number',
        "data_source_id" integer,
        "value_column" varchar(100) DEFAULT 'numeric_value',
        "filter_criteria" jsonb DEFAULT '{}'::jsonb,
        "created_at" timestamp with time zone DEFAULT now(),
        "updated_at" timestamp with time zone DEFAULT now(),
        CONSTRAINT "report_card_measures_measure_name_unique" UNIQUE("measure_name")
    );
EXCEPTION
    WHEN duplicate_table THEN NULL;
END $$;

-- Create report_card_results table
DO $$
BEGIN
    CREATE TABLE "report_card_results" (
        "result_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
        "practice_uid" integer NOT NULL,
        "organization_id" uuid,
        "report_card_month" date NOT NULL,
        "generated_at" timestamp with time zone DEFAULT now(),
        "overall_score" numeric(5, 2),
        "size_bucket" varchar(20),
        "percentile_rank" numeric(5, 2),
        "insights" jsonb,
        "measure_scores" jsonb,
        CONSTRAINT "uq_report_card_practice_month" UNIQUE("practice_uid","report_card_month")
    );
EXCEPTION
    WHEN duplicate_table THEN NULL;
END $$;

-- Create report_card_statistics table
DO $$
BEGIN
    CREATE TABLE "report_card_statistics" (
        "statistic_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "report_card_statistics_statistic_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
        "practice_uid" integer NOT NULL,
        "organization_id" uuid,
        "measure_name" varchar(100) NOT NULL,
        "time_period" varchar(20) DEFAULT 'Monthly',
        "period_date" timestamp with time zone NOT NULL,
        "value" numeric(18, 2) NOT NULL,
        "collected_at" timestamp with time zone DEFAULT now(),
        CONSTRAINT "uq_report_card_statistics" UNIQUE("practice_uid","measure_name","time_period","period_date")
    );
EXCEPTION
    WHEN duplicate_table THEN NULL;
END $$;

-- Create report_card_trends table
DO $$
BEGIN
    CREATE TABLE "report_card_trends" (
        "trend_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "report_card_trends_trend_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
        "practice_uid" integer NOT NULL,
        "organization_id" uuid,
        "measure_name" varchar(100) NOT NULL,
        "trend_period" varchar(20) NOT NULL,
        "trend_direction" varchar(20) NOT NULL,
        "trend_percentage" numeric(8, 2),
        "calculated_at" timestamp with time zone DEFAULT now(),
        CONSTRAINT "uq_report_card_trends" UNIQUE("practice_uid","measure_name","trend_period")
    );
EXCEPTION
    WHEN duplicate_table THEN NULL;
END $$;

-- ============================================================================
-- PART 3: DROP OLD INDEXES (idempotent)
-- ============================================================================

DROP INDEX IF EXISTS "idx_work_item_field_values_work_item_field";
DROP INDEX IF EXISTS "idx_unique_transition";
DROP INDEX IF EXISTS "idx_unique_watcher";

-- ============================================================================
-- PART 4: ALTER COLUMNS
-- ============================================================================

DO $$
BEGIN
    ALTER TABLE "chart_provider_colors" ALTER COLUMN "color_palette_id" SET DEFAULT 'tableau20';
EXCEPTION
    WHEN others THEN NULL;
END $$;

-- ============================================================================
-- PART 5: ADD COLUMNS TO chart_definitions
-- ============================================================================

DO $$
BEGIN
    ALTER TABLE "chart_definitions" ADD COLUMN "drill_down_enabled" boolean DEFAULT false;
EXCEPTION
    WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "chart_definitions" ADD COLUMN "drill_down_type" text;
EXCEPTION
    WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "chart_definitions" ADD COLUMN "drill_down_target_chart_id" uuid;
EXCEPTION
    WHEN duplicate_column THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "chart_definitions" ADD COLUMN "drill_down_button_label" text DEFAULT 'Drill Down';
EXCEPTION
    WHEN duplicate_column THEN NULL;
END $$;

-- ============================================================================
-- PART 6: CREATE INDEXES (idempotent)
-- ============================================================================

-- Announcements indexes
CREATE INDEX IF NOT EXISTS "idx_announcements_publish_at" ON "announcements" USING btree ("publish_at");
CREATE INDEX IF NOT EXISTS "idx_announcements_target_type" ON "announcements" USING btree ("target_type");
CREATE INDEX IF NOT EXISTS "idx_announcements_is_active" ON "announcements" USING btree ("is_active");
CREATE INDEX IF NOT EXISTS "idx_announcements_created_at" ON "announcements" USING btree ("created_at");
CREATE INDEX IF NOT EXISTS "idx_announcements_deleted_at" ON "announcements" USING btree ("deleted_at");

-- Announcement recipients indexes
CREATE INDEX IF NOT EXISTS "idx_announcement_recipients_announcement" ON "announcement_recipients" USING btree ("announcement_id");
CREATE INDEX IF NOT EXISTS "idx_announcement_recipients_user" ON "announcement_recipients" USING btree ("user_id");

-- Announcement reads indexes
CREATE INDEX IF NOT EXISTS "idx_announcement_reads_announcement" ON "announcement_reads" USING btree ("announcement_id");
CREATE INDEX IF NOT EXISTS "idx_announcement_reads_user" ON "announcement_reads" USING btree ("user_id");

-- Report card indexes
CREATE INDEX IF NOT EXISTS "idx_practice_size_buckets_bucket" ON "practice_size_buckets" USING btree ("size_bucket");
CREATE INDEX IF NOT EXISTS "idx_practice_size_buckets_org" ON "practice_size_buckets" USING btree ("organization_id");
CREATE INDEX IF NOT EXISTS "idx_report_card_measures_active" ON "report_card_measures" USING btree ("is_active");
CREATE INDEX IF NOT EXISTS "idx_report_card_measures_name" ON "report_card_measures" USING btree ("measure_name");
CREATE INDEX IF NOT EXISTS "idx_report_card_measures_data_source" ON "report_card_measures" USING btree ("data_source_id");
CREATE INDEX IF NOT EXISTS "idx_report_card_results_practice" ON "report_card_results" USING btree ("practice_uid");
CREATE INDEX IF NOT EXISTS "idx_report_card_results_generated" ON "report_card_results" USING btree ("generated_at");
CREATE INDEX IF NOT EXISTS "idx_report_card_results_bucket" ON "report_card_results" USING btree ("size_bucket");
CREATE INDEX IF NOT EXISTS "idx_report_card_results_org" ON "report_card_results" USING btree ("organization_id");
CREATE INDEX IF NOT EXISTS "idx_report_card_results_month" ON "report_card_results" USING btree ("report_card_month");
CREATE INDEX IF NOT EXISTS "idx_report_card_results_practice_month" ON "report_card_results" USING btree ("practice_uid","report_card_month");
CREATE INDEX IF NOT EXISTS "idx_report_card_statistics_practice" ON "report_card_statistics" USING btree ("practice_uid");
CREATE INDEX IF NOT EXISTS "idx_report_card_statistics_measure" ON "report_card_statistics" USING btree ("measure_name");
CREATE INDEX IF NOT EXISTS "idx_report_card_statistics_period" ON "report_card_statistics" USING btree ("period_date");
CREATE INDEX IF NOT EXISTS "idx_report_card_statistics_org" ON "report_card_statistics" USING btree ("organization_id");
CREATE INDEX IF NOT EXISTS "idx_report_card_trends_practice" ON "report_card_trends" USING btree ("practice_uid");
CREATE INDEX IF NOT EXISTS "idx_report_card_trends_period" ON "report_card_trends" USING btree ("trend_period");
CREATE INDEX IF NOT EXISTS "idx_report_card_trends_measure" ON "report_card_trends" USING btree ("measure_name");
CREATE INDEX IF NOT EXISTS "idx_report_card_trends_org" ON "report_card_trends" USING btree ("organization_id");
CREATE INDEX IF NOT EXISTS "idx_work_items_org_status" ON "work_items" USING btree ("organization_id","status_id");

-- ============================================================================
-- PART 7: ADD FOREIGN KEY CONSTRAINTS (idempotent)
-- ============================================================================

-- Announcement FK constraints
DO $$
BEGIN
    ALTER TABLE "announcements" ADD CONSTRAINT "announcements_created_by_users_user_id_fk"
    FOREIGN KEY ("created_by") REFERENCES "public"."users"("user_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "announcement_recipients" ADD CONSTRAINT "announcement_recipients_announcement_id_announcements_announcement_id_fk"
    FOREIGN KEY ("announcement_id") REFERENCES "public"."announcements"("announcement_id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "announcement_recipients" ADD CONSTRAINT "announcement_recipients_user_id_users_user_id_fk"
    FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "announcement_reads" ADD CONSTRAINT "announcement_reads_announcement_id_announcements_announcement_id_fk"
    FOREIGN KEY ("announcement_id") REFERENCES "public"."announcements"("announcement_id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "announcement_reads" ADD CONSTRAINT "announcement_reads_user_id_users_user_id_fk"
    FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

-- Report card FK constraints
DO $$
BEGIN
    ALTER TABLE "practice_size_buckets" ADD CONSTRAINT "practice_size_buckets_organization_id_organizations_organization_id_fk"
    FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE set null ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "report_card_measures" ADD CONSTRAINT "report_card_measures_data_source_id_chart_data_sources_data_source_id_fk"
    FOREIGN KEY ("data_source_id") REFERENCES "public"."chart_data_sources"("data_source_id") ON DELETE set null ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "report_card_results" ADD CONSTRAINT "report_card_results_organization_id_organizations_organization_id_fk"
    FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE set null ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "report_card_statistics" ADD CONSTRAINT "report_card_statistics_organization_id_organizations_organization_id_fk"
    FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE set null ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "report_card_trends" ADD CONSTRAINT "report_card_trends_organization_id_organizations_organization_id_fk"
    FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE set null ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

-- Other FK constraints
DO $$
BEGIN
    ALTER TABLE "account_security" ADD CONSTRAINT "account_security_user_id_users_user_id_fk"
    FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "chart_definitions" ADD CONSTRAINT "chart_definitions_drill_down_target_chart_id_chart_definitions_chart_definition_id_fk"
    FOREIGN KEY ("drill_down_target_chart_id") REFERENCES "public"."chart_definitions"("chart_definition_id") ON DELETE set null ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "login_attempts" ADD CONSTRAINT "login_attempts_user_id_users_user_id_fk"
    FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE set null ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "organizations" ADD CONSTRAINT "organizations_parent_organization_id_organizations_organization_id_fk"
    FOREIGN KEY ("parent_organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE set null ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_user_id_users_user_id_fk"
    FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "token_blacklist" ADD CONSTRAINT "token_blacklist_user_id_users_user_id_fk"
    FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "user_organizations" ADD CONSTRAINT "user_organizations_user_id_users_user_id_fk"
    FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "user_roles" ADD CONSTRAINT "user_roles_user_id_users_user_id_fk"
    FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "user_roles" ADD CONSTRAINT "user_roles_granted_by_users_user_id_fk"
    FOREIGN KEY ("granted_by") REFERENCES "public"."users"("user_id") ON DELETE set null ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "user_sessions" ADD CONSTRAINT "user_sessions_user_id_users_user_id_fk"
    FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "work_item_comments" ADD CONSTRAINT "work_item_comments_parent_comment_id_work_item_comments_work_item_comment_id_fk"
    FOREIGN KEY ("parent_comment_id") REFERENCES "public"."work_item_comments"("work_item_comment_id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "work_items" ADD CONSTRAINT "work_items_parent_work_item_id_work_items_work_item_id_fk"
    FOREIGN KEY ("parent_work_item_id") REFERENCES "public"."work_items"("work_item_id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "work_items" ADD CONSTRAINT "work_items_root_work_item_id_work_items_work_item_id_fk"
    FOREIGN KEY ("root_work_item_id") REFERENCES "public"."work_items"("work_item_id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

-- ============================================================================
-- PART 8: ADD UNIQUE CONSTRAINTS (idempotent)
-- ============================================================================

DO $$
BEGIN
    ALTER TABLE "work_item_field_values" ADD CONSTRAINT "uq_work_item_field_values_work_item_field" UNIQUE("work_item_id","work_item_field_id");
EXCEPTION
    WHEN duplicate_table THEN NULL;
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "work_item_status_transitions" ADD CONSTRAINT "uq_transition_type_from_to" UNIQUE("work_item_type_id","from_status_id","to_status_id");
EXCEPTION
    WHEN duplicate_table THEN NULL;
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE "work_item_watchers" ADD CONSTRAINT "uq_watchers_work_item_user" UNIQUE("work_item_id","user_id");
EXCEPTION
    WHEN duplicate_table THEN NULL;
    WHEN duplicate_object THEN NULL;
END $$;
