-- Migration: Report Card Tables + Pending Schema Updates
-- This migration adds:
-- 1. Practice Report Card feature tables (5 new tables)
-- 2. Drill-down columns for chart_definitions
-- 3. Status transition unique constraint
-- All statements made idempotent for safe reruns

-- ============================================================================
-- Report Card Tables
-- ============================================================================

-- Table: practice_size_buckets
CREATE TABLE IF NOT EXISTS "practice_size_buckets" (
	"bucket_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "practice_size_buckets_bucket_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"practice_uid" integer NOT NULL,
	"organization_id" uuid,
	"size_bucket" varchar(20) NOT NULL,
	"monthly_charges_avg" numeric(18, 2),
	"percentile" numeric(5, 2),
	"calculated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "practice_size_buckets_practice_uid_unique" UNIQUE("practice_uid")
);

-- Table: report_card_measures
CREATE TABLE IF NOT EXISTS "report_card_measures" (
	"measure_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "report_card_measures_measure_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"measure_name" varchar(100) NOT NULL,
	"display_name" varchar(100) NOT NULL,
	"weight" numeric(3, 1) DEFAULT '5.0',
	"is_active" boolean DEFAULT true,
	"higher_is_better" boolean DEFAULT true,
	"format_type" varchar(20) DEFAULT 'number',
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "report_card_measures_measure_name_unique" UNIQUE("measure_name")
);

-- Table: report_card_results
CREATE TABLE IF NOT EXISTS "report_card_results" (
	"result_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"practice_uid" integer NOT NULL,
	"organization_id" uuid,
	"generated_at" timestamp with time zone DEFAULT now(),
	"overall_score" numeric(5, 2),
	"size_bucket" varchar(20),
	"percentile_rank" numeric(5, 2),
	"insights" jsonb,
	"measure_scores" jsonb
);

-- Table: report_card_statistics
CREATE TABLE IF NOT EXISTS "report_card_statistics" (
	"statistic_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "report_card_statistics_statistic_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"practice_uid" integer NOT NULL,
	"organization_id" uuid,
	"measure_name" varchar(100) NOT NULL,
	"time_period" varchar(20) DEFAULT 'Monthly',
	"period_date" timestamp with time zone NOT NULL,
	"value" numeric(18, 2) NOT NULL,
	CONSTRAINT "uq_report_card_statistics" UNIQUE("practice_uid","measure_name","time_period","period_date")
);

-- Table: report_card_trends
CREATE TABLE IF NOT EXISTS "report_card_trends" (
	"trend_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "report_card_trends_trend_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"practice_uid" integer NOT NULL,
	"organization_id" uuid,
	"measure_name" varchar(100) NOT NULL,
	"trend_period" varchar(20) NOT NULL,
	"trend_direction" varchar(20) NOT NULL,
	"trend_percentage" numeric(8, 2),
	"calculated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "uq_report_card_trends" UNIQUE("practice_uid","measure_name","trend_period")
);

-- Add collected_at column if missing from report_card_statistics
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'report_card_statistics' AND column_name = 'collected_at'
  ) THEN
    ALTER TABLE "report_card_statistics" ADD COLUMN "collected_at" timestamp with time zone DEFAULT now();
  END IF;
END $$;

-- ============================================================================
-- Foreign Key Constraints (idempotent)
-- ============================================================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'practice_size_buckets_organization_id_organizations_organization_id_fk'
  ) THEN
    ALTER TABLE "practice_size_buckets" ADD CONSTRAINT "practice_size_buckets_organization_id_organizations_organization_id_fk"
      FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE set null ON UPDATE no action;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'report_card_results_organization_id_organizations_organization_id_fk'
  ) THEN
    ALTER TABLE "report_card_results" ADD CONSTRAINT "report_card_results_organization_id_organizations_organization_id_fk"
      FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE set null ON UPDATE no action;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'report_card_statistics_organization_id_organizations_organization_id_fk'
  ) THEN
    ALTER TABLE "report_card_statistics" ADD CONSTRAINT "report_card_statistics_organization_id_organizations_organization_id_fk"
      FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE set null ON UPDATE no action;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'report_card_trends_organization_id_organizations_organization_id_fk'
  ) THEN
    ALTER TABLE "report_card_trends" ADD CONSTRAINT "report_card_trends_organization_id_organizations_organization_id_fk"
      FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE set null ON UPDATE no action;
  END IF;
END $$;

-- ============================================================================
-- Indexes for Report Card Tables (idempotent)
-- ============================================================================

CREATE INDEX IF NOT EXISTS "idx_practice_size_buckets_bucket" ON "practice_size_buckets" USING btree ("size_bucket");
CREATE INDEX IF NOT EXISTS "idx_practice_size_buckets_org" ON "practice_size_buckets" USING btree ("organization_id");
CREATE INDEX IF NOT EXISTS "idx_report_card_measures_active" ON "report_card_measures" USING btree ("is_active");
CREATE INDEX IF NOT EXISTS "idx_report_card_measures_name" ON "report_card_measures" USING btree ("measure_name");
CREATE INDEX IF NOT EXISTS "idx_report_card_results_practice" ON "report_card_results" USING btree ("practice_uid");
CREATE INDEX IF NOT EXISTS "idx_report_card_results_generated" ON "report_card_results" USING btree ("generated_at");
CREATE INDEX IF NOT EXISTS "idx_report_card_results_bucket" ON "report_card_results" USING btree ("size_bucket");
CREATE INDEX IF NOT EXISTS "idx_report_card_results_org" ON "report_card_results" USING btree ("organization_id");
CREATE INDEX IF NOT EXISTS "idx_report_card_statistics_practice" ON "report_card_statistics" USING btree ("practice_uid");
CREATE INDEX IF NOT EXISTS "idx_report_card_statistics_measure" ON "report_card_statistics" USING btree ("measure_name");
CREATE INDEX IF NOT EXISTS "idx_report_card_statistics_period" ON "report_card_statistics" USING btree ("period_date");
CREATE INDEX IF NOT EXISTS "idx_report_card_statistics_org" ON "report_card_statistics" USING btree ("organization_id");
CREATE INDEX IF NOT EXISTS "idx_report_card_trends_practice" ON "report_card_trends" USING btree ("practice_uid");
CREATE INDEX IF NOT EXISTS "idx_report_card_trends_period" ON "report_card_trends" USING btree ("trend_period");
CREATE INDEX IF NOT EXISTS "idx_report_card_trends_measure" ON "report_card_trends" USING btree ("measure_name");
CREATE INDEX IF NOT EXISTS "idx_report_card_trends_org" ON "report_card_trends" USING btree ("organization_id");

-- ============================================================================
-- Seed Default Measures (idempotent with ON CONFLICT DO NOTHING)
-- ============================================================================

INSERT INTO "report_card_measures" ("measure_name", "display_name", "weight", "is_active", "higher_is_better", "format_type")
VALUES
  ('charges', 'Charges', 10.0, true, true, 'currency'),
  ('payments', 'Payments', 9.0, true, true, 'currency'),
  ('adjustments', 'Adjustments', 5.0, true, false, 'currency'),
  ('new_patients', 'New Patients', 8.0, true, true, 'number'),
  ('claims_submitted', 'Claims Submitted', 7.0, true, true, 'number'),
  ('denials', 'Denials', 6.0, true, false, 'number'),
  ('denial_rate', 'Denial Rate', 7.0, true, false, 'percentage'),
  ('collection_rate', 'Collection Rate', 9.0, true, true, 'percentage'),
  ('days_in_ar', 'Days in A/R', 8.0, true, false, 'number'),
  ('aged_ar_90plus', 'A/R Over 90 Days', 6.0, true, false, 'currency'),
  ('visit_count', 'Visit Count', 7.0, true, true, 'number'),
  ('avg_reimbursement', 'Avg Reimbursement', 8.0, true, true, 'currency')
ON CONFLICT ("measure_name") DO NOTHING;

-- ============================================================================
-- Other Pending Schema Changes (idempotent)
-- ============================================================================

-- Drop idx_unique_transition if it exists (replaced by proper constraint)
DROP INDEX IF EXISTS "idx_unique_transition";

-- Update chart_provider_colors default
DO $$
BEGIN
  -- This is a default change, no idempotency needed as ALTER COLUMN SET DEFAULT is safe to rerun
  ALTER TABLE "chart_provider_colors" ALTER COLUMN "color_palette_id" SET DEFAULT 'tableau20';
EXCEPTION
  WHEN undefined_column THEN NULL;
  WHEN undefined_table THEN NULL;
END $$;

-- Add drill_down columns to chart_definitions (idempotent)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'chart_definitions' AND column_name = 'drill_down_enabled'
  ) THEN
    ALTER TABLE "chart_definitions" ADD COLUMN "drill_down_enabled" boolean DEFAULT false;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'chart_definitions' AND column_name = 'drill_down_type'
  ) THEN
    ALTER TABLE "chart_definitions" ADD COLUMN "drill_down_type" text;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'chart_definitions' AND column_name = 'drill_down_target_chart_id'
  ) THEN
    ALTER TABLE "chart_definitions" ADD COLUMN "drill_down_target_chart_id" uuid;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'chart_definitions' AND column_name = 'drill_down_button_label'
  ) THEN
    ALTER TABLE "chart_definitions" ADD COLUMN "drill_down_button_label" text DEFAULT 'Drill Down';
  END IF;
END $$;

-- Add unique constraint to work_item_status_transitions (idempotent)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'uq_transition_type_from_to'
  ) THEN
    ALTER TABLE "work_item_status_transitions" ADD CONSTRAINT "uq_transition_type_from_to"
      UNIQUE("work_item_type_id","from_status_id","to_status_id");
  END IF;
END $$;

-- Foreign Key Constraints (idempotent)
-- ============================================================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'practice_size_buckets_organization_id_organizations_organization_id_fk'
  ) THEN
    ALTER TABLE "practice_size_buckets" ADD CONSTRAINT "practice_size_buckets_organization_id_organizations_organization_id_fk"
      FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE set null ON UPDATE no action;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'report_card_results_organization_id_organizations_organization_id_fk'
  ) THEN
    ALTER TABLE "report_card_results" ADD CONSTRAINT "report_card_results_organization_id_organizations_organization_id_fk"
      FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE set null ON UPDATE no action;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'report_card_statistics_organization_id_organizations_organization_id_fk'
  ) THEN
    ALTER TABLE "report_card_statistics" ADD CONSTRAINT "report_card_statistics_organization_id_organizations_organization_id_fk"
      FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE set null ON UPDATE no action;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'report_card_trends_organization_id_organizations_organization_id_fk'
  ) THEN
    ALTER TABLE "report_card_trends" ADD CONSTRAINT "report_card_trends_organization_id_organizations_organization_id_fk"
      FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE set null ON UPDATE no action;
  END IF;
END $$;

-- ============================================================================
-- Indexes for Report Card Tables (idempotent)
-- ============================================================================

CREATE INDEX IF NOT EXISTS "idx_practice_size_buckets_bucket" ON "practice_size_buckets" USING btree ("size_bucket");
CREATE INDEX IF NOT EXISTS "idx_practice_size_buckets_org" ON "practice_size_buckets" USING btree ("organization_id");
CREATE INDEX IF NOT EXISTS "idx_report_card_measures_active" ON "report_card_measures" USING btree ("is_active");
CREATE INDEX IF NOT EXISTS "idx_report_card_measures_name" ON "report_card_measures" USING btree ("measure_name");
CREATE INDEX IF NOT EXISTS "idx_report_card_results_practice" ON "report_card_results" USING btree ("practice_uid");
CREATE INDEX IF NOT EXISTS "idx_report_card_results_generated" ON "report_card_results" USING btree ("generated_at");
CREATE INDEX IF NOT EXISTS "idx_report_card_results_bucket" ON "report_card_results" USING btree ("size_bucket");
CREATE INDEX IF NOT EXISTS "idx_report_card_results_org" ON "report_card_results" USING btree ("organization_id");
CREATE INDEX IF NOT EXISTS "idx_report_card_statistics_practice" ON "report_card_statistics" USING btree ("practice_uid");
CREATE INDEX IF NOT EXISTS "idx_report_card_statistics_measure" ON "report_card_statistics" USING btree ("measure_name");
CREATE INDEX IF NOT EXISTS "idx_report_card_statistics_period" ON "report_card_statistics" USING btree ("period_date");
CREATE INDEX IF NOT EXISTS "idx_report_card_statistics_org" ON "report_card_statistics" USING btree ("organization_id");
CREATE INDEX IF NOT EXISTS "idx_report_card_trends_practice" ON "report_card_trends" USING btree ("practice_uid");
CREATE INDEX IF NOT EXISTS "idx_report_card_trends_period" ON "report_card_trends" USING btree ("trend_period");
CREATE INDEX IF NOT EXISTS "idx_report_card_trends_measure" ON "report_card_trends" USING btree ("measure_name");
CREATE INDEX IF NOT EXISTS "idx_report_card_trends_org" ON "report_card_trends" USING btree ("organization_id");

-- ============================================================================
-- Seed Default Measures (idempotent with ON CONFLICT DO NOTHING)
-- ============================================================================

INSERT INTO "report_card_measures" ("measure_name", "display_name", "weight", "is_active", "higher_is_better", "format_type")
VALUES
  ('charges', 'Charges', 10.0, true, true, 'currency'),
  ('payments', 'Payments', 9.0, true, true, 'currency'),
  ('adjustments', 'Adjustments', 5.0, true, false, 'currency'),
  ('new_patients', 'New Patients', 8.0, true, true, 'number'),
  ('claims_submitted', 'Claims Submitted', 7.0, true, true, 'number'),
  ('denials', 'Denials', 6.0, true, false, 'number'),
  ('denial_rate', 'Denial Rate', 7.0, true, false, 'percentage'),
  ('collection_rate', 'Collection Rate', 9.0, true, true, 'percentage'),
  ('days_in_ar', 'Days in A/R', 8.0, true, false, 'number'),
  ('aged_ar_90plus', 'A/R Over 90 Days', 6.0, true, false, 'currency'),
  ('visit_count', 'Visit Count', 7.0, true, true, 'number'),
  ('avg_reimbursement', 'Avg Reimbursement', 8.0, true, true, 'currency')
ON CONFLICT ("measure_name") DO NOTHING;

-- ============================================================================
-- Other Pending Schema Changes (idempotent)
-- ============================================================================

-- Drop idx_unique_transition if it exists (replaced by proper constraint)
DROP INDEX IF EXISTS "idx_unique_transition";

-- Update chart_provider_colors default
DO $$
BEGIN
  -- This is a default change, no idempotency needed as ALTER COLUMN SET DEFAULT is safe to rerun
  ALTER TABLE "chart_provider_colors" ALTER COLUMN "color_palette_id" SET DEFAULT 'tableau20';
EXCEPTION
  WHEN undefined_column THEN NULL;
  WHEN undefined_table THEN NULL;
END $$;

-- Add drill_down columns to chart_definitions (idempotent)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'chart_definitions' AND column_name = 'drill_down_enabled'
  ) THEN
    ALTER TABLE "chart_definitions" ADD COLUMN "drill_down_enabled" boolean DEFAULT false;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'chart_definitions' AND column_name = 'drill_down_type'
  ) THEN
    ALTER TABLE "chart_definitions" ADD COLUMN "drill_down_type" text;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'chart_definitions' AND column_name = 'drill_down_target_chart_id'
  ) THEN
    ALTER TABLE "chart_definitions" ADD COLUMN "drill_down_target_chart_id" uuid;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'chart_definitions' AND column_name = 'drill_down_button_label'
  ) THEN
    ALTER TABLE "chart_definitions" ADD COLUMN "drill_down_button_label" text DEFAULT 'Drill Down';
  END IF;
END $$;

-- Add unique constraint to work_item_status_transitions (idempotent)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'uq_transition_type_from_to'
  ) THEN
    ALTER TABLE "work_item_status_transitions" ADD CONSTRAINT "uq_transition_type_from_to"
      UNIQUE("work_item_type_id","from_status_id","to_status_id");
  END IF;
END $$;
